// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/autolytiq/backend/ent/aicounteroffer"
	"github.com/autolytiq/backend/ent/predicate"
)

// AICounterOfferDelete is the builder for deleting a AICounterOffer entity.
type AICounterOfferDelete struct {
	config
	hooks    []Hook
	mutation *AICounterOfferMutation
}

// Where appends a list predicates to the AICounterOfferDelete builder.
func (_d *AICounterOfferDelete) Where(ps ...predicate.AICounterOffer) *AICounterOfferDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AICounterOfferDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AICounterOfferDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AICounterOfferDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aicounteroffer.Table, sqlgraph.NewFieldSpec(aicounteroffer.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AICounterOfferDeleteOne is the builder for deleting a single AICounterOffer entity.
type AICounterOfferDeleteOne struct {
	_d *AICounterOfferDelete
}

// Where appends a list predicates to the AICounterOfferDelete builder.
func (_d *AICounterOfferDeleteOne) Where(ps ...predicate.AICounterOffer) *AICounterOfferDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AICounterOfferDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aicounteroffer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AICounterOfferDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
