// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/autolytiq/backend/ent/customer"
	"github.com/autolytiq/backend/ent/deal"
	"github.com/autolytiq/backend/ent/predicate"
	"github.com/autolytiq/backend/ent/tenant"
	"github.com/autolytiq/backend/ent/tradein"
	"github.com/autolytiq/backend/ent/user"
	"github.com/autolytiq/backend/ent/vehicle"
)

// DealQuery is the builder for querying Deal entities.
type DealQuery struct {
	config
	ctx             *QueryContext
	order           []deal.OrderOption
	inters          []Interceptor
	predicates      []predicate.Deal
	withTenant      *TenantQuery
	withCustomer    *CustomerQuery
	withVehicle     *VehicleQuery
	withSalesperson *UserQuery
	withTradeIns    *TradeInQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DealQuery builder.
func (_q *DealQuery) Where(ps ...predicate.Deal) *DealQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DealQuery) Limit(limit int) *DealQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DealQuery) Offset(offset int) *DealQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DealQuery) Unique(unique bool) *DealQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DealQuery) Order(o ...deal.OrderOption) *DealQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *DealQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deal.Table, deal.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deal.TenantTable, deal.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCustomer chains the current query on the "customer" edge.
func (_q *DealQuery) QueryCustomer() *CustomerQuery {
	query := (&CustomerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deal.Table, deal.FieldID, selector),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deal.CustomerTable, deal.CustomerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVehicle chains the current query on the "vehicle" edge.
func (_q *DealQuery) QueryVehicle() *VehicleQuery {
	query := (&VehicleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deal.Table, deal.FieldID, selector),
			sqlgraph.To(vehicle.Table, vehicle.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deal.VehicleTable, deal.VehicleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySalesperson chains the current query on the "salesperson" edge.
func (_q *DealQuery) QuerySalesperson() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deal.Table, deal.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deal.SalespersonTable, deal.SalespersonColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTradeIns chains the current query on the "trade_ins" edge.
func (_q *DealQuery) QueryTradeIns() *TradeInQuery {
	query := (&TradeInClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deal.Table, deal.FieldID, selector),
			sqlgraph.To(tradein.Table, tradein.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, deal.TradeInsTable, deal.TradeInsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Deal entity from the query.
// Returns a *NotFoundError when no Deal was found.
func (_q *DealQuery) First(ctx context.Context) (*Deal, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deal.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DealQuery) FirstX(ctx context.Context) *Deal {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Deal ID from the query.
// Returns a *NotFoundError when no Deal ID was found.
func (_q *DealQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deal.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DealQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Deal entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Deal entity is found.
// Returns a *NotFoundError when no Deal entities are found.
func (_q *DealQuery) Only(ctx context.Context) (*Deal, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deal.Label}
	default:
		return nil, &NotSingularError{deal.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DealQuery) OnlyX(ctx context.Context) *Deal {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Deal ID in the query.
// Returns a *NotSingularError when more than one Deal ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DealQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deal.Label}
	default:
		err = &NotSingularError{deal.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DealQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Deals.
func (_q *DealQuery) All(ctx context.Context) ([]*Deal, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Deal, *DealQuery]()
	return withInterceptors[[]*Deal](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DealQuery) AllX(ctx context.Context) []*Deal {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Deal IDs.
func (_q *DealQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(deal.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DealQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DealQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DealQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DealQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DealQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DealQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DealQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DealQuery) Clone() *DealQuery {
	if _q == nil {
		return nil
	}
	return &DealQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]deal.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.Deal{}, _q.predicates...),
		withTenant:      _q.withTenant.Clone(),
		withCustomer:    _q.withCustomer.Clone(),
		withVehicle:     _q.withVehicle.Clone(),
		withSalesperson: _q.withSalesperson.Clone(),
		withTradeIns:    _q.withTradeIns.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DealQuery) WithTenant(opts ...func(*TenantQuery)) *DealQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithCustomer tells the query-builder to eager-load the nodes that are connected to
// the "customer" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DealQuery) WithCustomer(opts ...func(*CustomerQuery)) *DealQuery {
	query := (&CustomerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCustomer = query
	return _q
}

// WithVehicle tells the query-builder to eager-load the nodes that are connected to
// the "vehicle" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DealQuery) WithVehicle(opts ...func(*VehicleQuery)) *DealQuery {
	query := (&VehicleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVehicle = query
	return _q
}

// WithSalesperson tells the query-builder to eager-load the nodes that are connected to
// the "salesperson" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DealQuery) WithSalesperson(opts ...func(*UserQuery)) *DealQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSalesperson = query
	return _q
}

// WithTradeIns tells the query-builder to eager-load the nodes that are connected to
// the "trade_ins" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DealQuery) WithTradeIns(opts ...func(*TradeInQuery)) *DealQuery {
	query := (&TradeInClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTradeIns = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Deal.Query().
//		GroupBy(deal.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DealQuery) GroupBy(field string, fields ...string) *DealGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DealGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = deal.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.Deal.Query().
//		Select(deal.FieldTenantID).
//		Scan(ctx, &v)
func (_q *DealQuery) Select(fields ...string) *DealSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DealSelect{DealQuery: _q}
	sbuild.label = deal.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DealSelect configured with the given aggregations.
func (_q *DealQuery) Aggregate(fns ...AggregateFunc) *DealSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DealQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !deal.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DealQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Deal, error) {
	var (
		nodes       = []*Deal{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withTenant != nil,
			_q.withCustomer != nil,
			_q.withVehicle != nil,
			_q.withSalesperson != nil,
			_q.withTradeIns != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Deal).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Deal{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *Deal, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCustomer; query != nil {
		if err := _q.loadCustomer(ctx, query, nodes, nil,
			func(n *Deal, e *Customer) { n.Edges.Customer = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVehicle; query != nil {
		if err := _q.loadVehicle(ctx, query, nodes, nil,
			func(n *Deal, e *Vehicle) { n.Edges.Vehicle = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSalesperson; query != nil {
		if err := _q.loadSalesperson(ctx, query, nodes, nil,
			func(n *Deal, e *User) { n.Edges.Salesperson = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTradeIns; query != nil {
		if err := _q.loadTradeIns(ctx, query, nodes,
			func(n *Deal) { n.Edges.TradeIns = []*TradeIn{} },
			func(n *Deal, e *TradeIn) { n.Edges.TradeIns = append(n.Edges.TradeIns, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DealQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*Deal, init func(*Deal), assign func(*Deal, *Tenant)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Deal)
	for i := range nodes {
		fk := nodes[i].TenantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DealQuery) loadCustomer(ctx context.Context, query *CustomerQuery, nodes []*Deal, init func(*Deal), assign func(*Deal, *Customer)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Deal)
	for i := range nodes {
		if nodes[i].CustomerID == nil {
			continue
		}
		fk := *nodes[i].CustomerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(customer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "customer_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DealQuery) loadVehicle(ctx context.Context, query *VehicleQuery, nodes []*Deal, init func(*Deal), assign func(*Deal, *Vehicle)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Deal)
	for i := range nodes {
		if nodes[i].VehicleID == nil {
			continue
		}
		fk := *nodes[i].VehicleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(vehicle.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "vehicle_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DealQuery) loadSalesperson(ctx context.Context, query *UserQuery, nodes []*Deal, init func(*Deal), assign func(*Deal, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Deal)
	for i := range nodes {
		if nodes[i].SalespersonID == nil {
			continue
		}
		fk := *nodes[i].SalespersonID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "salesperson_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DealQuery) loadTradeIns(ctx context.Context, query *TradeInQuery, nodes []*Deal, init func(*Deal), assign func(*Deal, *TradeIn)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Deal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tradein.FieldDealID)
	}
	query.Where(predicate.TradeIn(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(deal.TradeInsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DealID
		if fk == nil {
			return fmt.Errorf(`foreign-key "deal_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "deal_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DealQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DealQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deal.Table, deal.Columns, sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deal.FieldID)
		for i := range fields {
			if fields[i] != deal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(deal.FieldTenantID)
		}
		if _q.withCustomer != nil {
			_spec.Node.AddColumnOnce(deal.FieldCustomerID)
		}
		if _q.withVehicle != nil {
			_spec.Node.AddColumnOnce(deal.FieldVehicleID)
		}
		if _q.withSalesperson != nil {
			_spec.Node.AddColumnOnce(deal.FieldSalespersonID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DealQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(deal.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = deal.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DealGroupBy is the group-by builder for Deal entities.
type DealGroupBy struct {
	selector
	build *DealQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DealGroupBy) Aggregate(fns ...AggregateFunc) *DealGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DealGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DealQuery, *DealGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DealGroupBy) sqlScan(ctx context.Context, root *DealQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DealSelect is the builder for selecting fields of Deal entities.
type DealSelect struct {
	*DealQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DealSelect) Aggregate(fns ...AggregateFunc) *DealSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DealSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DealQuery, *DealSelect](ctx, _s.DealQuery, _s, _s.inters, v)
}

func (_s *DealSelect) sqlScan(ctx context.Context, root *DealQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
