// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/autolytiq/backend/ent/dealworksheet"
	"github.com/autolytiq/backend/ent/predicate"
)

// DealWorksheetDelete is the builder for deleting a DealWorksheet entity.
type DealWorksheetDelete struct {
	config
	hooks    []Hook
	mutation *DealWorksheetMutation
}

// Where appends a list predicates to the DealWorksheetDelete builder.
func (_d *DealWorksheetDelete) Where(ps ...predicate.DealWorksheet) *DealWorksheetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DealWorksheetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DealWorksheetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DealWorksheetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dealworksheet.Table, sqlgraph.NewFieldSpec(dealworksheet.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DealWorksheetDeleteOne is the builder for deleting a single DealWorksheet entity.
type DealWorksheetDeleteOne struct {
	_d *DealWorksheetDelete
}

// Where appends a list predicates to the DealWorksheetDelete builder.
func (_d *DealWorksheetDeleteOne) Where(ps ...predicate.DealWorksheet) *DealWorksheetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DealWorksheetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dealworksheet.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DealWorksheetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
