// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/autolytiq/backend/ent/leadscore"
	"github.com/autolytiq/backend/ent/predicate"
)

// LeadScoreUpdate is the builder for updating LeadScore entities.
type LeadScoreUpdate struct {
	config
	hooks    []Hook
	mutation *LeadScoreMutation
}

// Where appends a list predicates to the LeadScoreUpdate builder.
func (_u *LeadScoreUpdate) Where(ps ...predicate.LeadScore) *LeadScoreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the LeadScoreMutation object of the builder.
func (_u *LeadScoreUpdate) Mutation() *LeadScoreMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LeadScoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LeadScoreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LeadScoreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LeadScoreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LeadScoreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(leadscore.Table, leadscore.Columns, sqlgraph.NewFieldSpec(leadscore.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{leadscore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LeadScoreUpdateOne is the builder for updating a single LeadScore entity.
type LeadScoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LeadScoreMutation
}

// Mutation returns the LeadScoreMutation object of the builder.
func (_u *LeadScoreUpdateOne) Mutation() *LeadScoreMutation {
	return _u.mutation
}

// Where appends a list predicates to the LeadScoreUpdate builder.
func (_u *LeadScoreUpdateOne) Where(ps ...predicate.LeadScore) *LeadScoreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LeadScoreUpdateOne) Select(field string, fields ...string) *LeadScoreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LeadScore entity.
func (_u *LeadScoreUpdateOne) Save(ctx context.Context) (*LeadScore, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LeadScoreUpdateOne) SaveX(ctx context.Context) *LeadScore {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LeadScoreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LeadScoreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LeadScoreUpdateOne) sqlSave(ctx context.Context) (_node *LeadScore, err error) {
	_spec := sqlgraph.NewUpdateSpec(leadscore.Table, leadscore.Columns, sqlgraph.NewFieldSpec(leadscore.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LeadScore.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, leadscore.FieldID)
		for _, f := range fields {
			if !leadscore.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != leadscore.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &LeadScore{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{leadscore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
