// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/autolytiq/backend/ent/note"
	"github.com/autolytiq/backend/ent/predicate"
	"github.com/autolytiq/backend/ent/tenant"
	"github.com/autolytiq/backend/ent/user"
)

// NoteUpdate is the builder for updating Note entities.
type NoteUpdate struct {
	config
	hooks    []Hook
	mutation *NoteMutation
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdate) Where(ps ...predicate.Note) *NoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *NoteUpdate) SetTenantID(v string) *NoteUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableTenantID(v *string) *NoteUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCreatedByID sets the "created_by_id" field.
func (_u *NoteUpdate) SetCreatedByID(v string) *NoteUpdate {
	_u.mutation.SetCreatedByID(v)
	return _u
}

// SetNillableCreatedByID sets the "created_by_id" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableCreatedByID(v *string) *NoteUpdate {
	if v != nil {
		_u.SetCreatedByID(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *NoteUpdate) SetEntityType(v string) *NoteUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableEntityType(v *string) *NoteUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *NoteUpdate) SetEntityID(v string) *NoteUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableEntityID(v *string) *NoteUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NoteUpdate) SetContent(v string) *NoteUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableContent(v *string) *NoteUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *NoteUpdate) SetIsPinned(v bool) *NoteUpdate {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableIsPinned(v *bool) *NoteUpdate {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NoteUpdate) SetUpdatedAt(v time.Time) *NoteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *NoteUpdate) SetTenant(v *Tenant) *NoteUpdate {
	return _u.SetTenantID(v.ID)
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *NoteUpdate) SetCreatedBy(v *User) *NoteUpdate {
	return _u.SetCreatedByID(v.ID)
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdate) Mutation() *NoteMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *NoteUpdate) ClearTenant() *NoteUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *NoteUpdate) ClearCreatedBy() *NoteUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NoteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NoteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := note.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := note.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Note.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedByID(); ok {
		if err := note.CreatedByIDValidator(v); err != nil {
			return &ValidationError{Name: "created_by_id", err: fmt.Errorf(`ent: validator failed for field "Note.created_by_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := note.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Note.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityID(); ok {
		if err := note.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "Note.entity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := note.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Note.content": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.tenant"`)
	}
	if _u.mutation.CreatedByCleared() && len(_u.mutation.CreatedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.created_by"`)
	}
	return nil
}

func (_u *NoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(note.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(note.FieldEntityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(note.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(note.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(note.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.TenantTable,
			Columns: []string{note.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.TenantTable,
			Columns: []string{note.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.CreatedByTable,
			Columns: []string{note.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.CreatedByTable,
			Columns: []string{note.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NoteUpdateOne is the builder for updating a single Note entity.
type NoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoteMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *NoteUpdateOne) SetTenantID(v string) *NoteUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableTenantID(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCreatedByID sets the "created_by_id" field.
func (_u *NoteUpdateOne) SetCreatedByID(v string) *NoteUpdateOne {
	_u.mutation.SetCreatedByID(v)
	return _u
}

// SetNillableCreatedByID sets the "created_by_id" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableCreatedByID(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetCreatedByID(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *NoteUpdateOne) SetEntityType(v string) *NoteUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableEntityType(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *NoteUpdateOne) SetEntityID(v string) *NoteUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableEntityID(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NoteUpdateOne) SetContent(v string) *NoteUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableContent(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *NoteUpdateOne) SetIsPinned(v bool) *NoteUpdateOne {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableIsPinned(v *bool) *NoteUpdateOne {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NoteUpdateOne) SetUpdatedAt(v time.Time) *NoteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *NoteUpdateOne) SetTenant(v *Tenant) *NoteUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *NoteUpdateOne) SetCreatedBy(v *User) *NoteUpdateOne {
	return _u.SetCreatedByID(v.ID)
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdateOne) Mutation() *NoteMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *NoteUpdateOne) ClearTenant() *NoteUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *NoteUpdateOne) ClearCreatedBy() *NoteUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdateOne) Where(ps ...predicate.Note) *NoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NoteUpdateOne) Select(field string, fields ...string) *NoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Note entity.
func (_u *NoteUpdateOne) Save(ctx context.Context) (*Note, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdateOne) SaveX(ctx context.Context) *Note {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NoteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := note.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := note.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Note.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedByID(); ok {
		if err := note.CreatedByIDValidator(v); err != nil {
			return &ValidationError{Name: "created_by_id", err: fmt.Errorf(`ent: validator failed for field "Note.created_by_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := note.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Note.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityID(); ok {
		if err := note.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "Note.entity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := note.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Note.content": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.tenant"`)
	}
	if _u.mutation.CreatedByCleared() && len(_u.mutation.CreatedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.created_by"`)
	}
	return nil
}

func (_u *NoteUpdateOne) sqlSave(ctx context.Context) (_node *Note, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Note.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, note.FieldID)
		for _, f := range fields {
			if !note.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != note.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(note.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(note.FieldEntityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(note.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(note.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(note.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.TenantTable,
			Columns: []string{note.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.TenantTable,
			Columns: []string{note.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.CreatedByTable,
			Columns: []string{note.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.CreatedByTable,
			Columns: []string{note.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Note{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
