// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/autolytiq/backend/ent/customer"
	"github.com/autolytiq/backend/ent/deal"
	"github.com/autolytiq/backend/ent/lead"
	"github.com/autolytiq/backend/ent/note"
	"github.com/autolytiq/backend/ent/notification"
	"github.com/autolytiq/backend/ent/predicate"
	"github.com/autolytiq/backend/ent/tenant"
	"github.com/autolytiq/backend/ent/tradein"
	"github.com/autolytiq/backend/ent/user"
	"github.com/autolytiq/backend/ent/vehicle"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubdomain sets the "subdomain" field.
func (_u *TenantUpdate) SetSubdomain(v string) *TenantUpdate {
	_u.mutation.SetSubdomain(v)
	return _u
}

// SetNillableSubdomain sets the "subdomain" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSubdomain(v *string) *TenantUpdate {
	if v != nil {
		_u.SetSubdomain(*v)
	}
	return _u
}

// SetPlan sets the "plan" field.
func (_u *TenantUpdate) SetPlan(v string) *TenantUpdate {
	_u.mutation.SetPlan(v)
	return _u
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_u *TenantUpdate) SetNillablePlan(v *string) *TenantUpdate {
	if v != nil {
		_u.SetPlan(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdate) SetStatus(v string) *TenantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableStatus(v *string) *TenantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettings sets the "settings" field.
func (_u *TenantUpdate) SetSettings(v map[string]interface{}) *TenantUpdate {
	_u.mutation.SetSettings(v)
	return _u
}

// SetBillingEmail sets the "billing_email" field.
func (_u *TenantUpdate) SetBillingEmail(v string) *TenantUpdate {
	_u.mutation.SetBillingEmail(v)
	return _u
}

// SetNillableBillingEmail sets the "billing_email" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableBillingEmail(v *string) *TenantUpdate {
	if v != nil {
		_u.SetBillingEmail(*v)
	}
	return _u
}

// SetSubscriptionEndsAt sets the "subscription_ends_at" field.
func (_u *TenantUpdate) SetSubscriptionEndsAt(v time.Time) *TenantUpdate {
	_u.mutation.SetSubscriptionEndsAt(v)
	return _u
}

// SetNillableSubscriptionEndsAt sets the "subscription_ends_at" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSubscriptionEndsAt(v *time.Time) *TenantUpdate {
	if v != nil {
		_u.SetSubscriptionEndsAt(*v)
	}
	return _u
}

// ClearSubscriptionEndsAt clears the value of the "subscription_ends_at" field.
func (_u *TenantUpdate) ClearSubscriptionEndsAt() *TenantUpdate {
	_u.mutation.ClearSubscriptionEndsAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdate) SetUpdatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *TenantUpdate) AddUserIDs(ids ...string) *TenantUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *TenantUpdate) AddUsers(v ...*User) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddCustomerIDs adds the "customers" edge to the Customer entity by IDs.
func (_u *TenantUpdate) AddCustomerIDs(ids ...string) *TenantUpdate {
	_u.mutation.AddCustomerIDs(ids...)
	return _u
}

// AddCustomers adds the "customers" edges to the Customer entity.
func (_u *TenantUpdate) AddCustomers(v ...*Customer) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCustomerIDs(ids...)
}

// AddVehicleIDs adds the "vehicles" edge to the Vehicle entity by IDs.
func (_u *TenantUpdate) AddVehicleIDs(ids ...string) *TenantUpdate {
	_u.mutation.AddVehicleIDs(ids...)
	return _u
}

// AddVehicles adds the "vehicles" edges to the Vehicle entity.
func (_u *TenantUpdate) AddVehicles(v ...*Vehicle) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVehicleIDs(ids...)
}

// AddDealIDs adds the "deals" edge to the Deal entity by IDs.
func (_u *TenantUpdate) AddDealIDs(ids ...string) *TenantUpdate {
	_u.mutation.AddDealIDs(ids...)
	return _u
}

// AddDeals adds the "deals" edges to the Deal entity.
func (_u *TenantUpdate) AddDeals(v ...*Deal) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDealIDs(ids...)
}

// AddLeadIDs adds the "leads" edge to the Lead entity by IDs.
func (_u *TenantUpdate) AddLeadIDs(ids ...string) *TenantUpdate {
	_u.mutation.AddLeadIDs(ids...)
	return _u
}

// AddLeads adds the "leads" edges to the Lead entity.
func (_u *TenantUpdate) AddLeads(v ...*Lead) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeadIDs(ids...)
}

// AddTradeInIDs adds the "trade_ins" edge to the TradeIn entity by IDs.
func (_u *TenantUpdate) AddTradeInIDs(ids ...string) *TenantUpdate {
	_u.mutation.AddTradeInIDs(ids...)
	return _u
}

// AddTradeIns adds the "trade_ins" edges to the TradeIn entity.
func (_u *TenantUpdate) AddTradeIns(v ...*TradeIn) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTradeInIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *TenantUpdate) AddNotificationIDs(ids ...string) *TenantUpdate {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *TenantUpdate) AddNotifications(v ...*Notification) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (_u *TenantUpdate) AddNoteIDs(ids ...string) *TenantUpdate {
	_u.mutation.AddNoteIDs(ids...)
	return _u
}

// AddNotes adds the "notes" edges to the Note entity.
func (_u *TenantUpdate) AddNotes(v ...*Note) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNoteIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *TenantUpdate) ClearUsers() *TenantUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *TenantUpdate) RemoveUserIDs(ids ...string) *TenantUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *TenantUpdate) RemoveUsers(v ...*User) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearCustomers clears all "customers" edges to the Customer entity.
func (_u *TenantUpdate) ClearCustomers() *TenantUpdate {
	_u.mutation.ClearCustomers()
	return _u
}

// RemoveCustomerIDs removes the "customers" edge to Customer entities by IDs.
func (_u *TenantUpdate) RemoveCustomerIDs(ids ...string) *TenantUpdate {
	_u.mutation.RemoveCustomerIDs(ids...)
	return _u
}

// RemoveCustomers removes "customers" edges to Customer entities.
func (_u *TenantUpdate) RemoveCustomers(v ...*Customer) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCustomerIDs(ids...)
}

// ClearVehicles clears all "vehicles" edges to the Vehicle entity.
func (_u *TenantUpdate) ClearVehicles() *TenantUpdate {
	_u.mutation.ClearVehicles()
	return _u
}

// RemoveVehicleIDs removes the "vehicles" edge to Vehicle entities by IDs.
func (_u *TenantUpdate) RemoveVehicleIDs(ids ...string) *TenantUpdate {
	_u.mutation.RemoveVehicleIDs(ids...)
	return _u
}

// RemoveVehicles removes "vehicles" edges to Vehicle entities.
func (_u *TenantUpdate) RemoveVehicles(v ...*Vehicle) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVehicleIDs(ids...)
}

// ClearDeals clears all "deals" edges to the Deal entity.
func (_u *TenantUpdate) ClearDeals() *TenantUpdate {
	_u.mutation.ClearDeals()
	return _u
}

// RemoveDealIDs removes the "deals" edge to Deal entities by IDs.
func (_u *TenantUpdate) RemoveDealIDs(ids ...string) *TenantUpdate {
	_u.mutation.RemoveDealIDs(ids...)
	return _u
}

// RemoveDeals removes "deals" edges to Deal entities.
func (_u *TenantUpdate) RemoveDeals(v ...*Deal) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDealIDs(ids...)
}

// ClearLeads clears all "leads" edges to the Lead entity.
func (_u *TenantUpdate) ClearLeads() *TenantUpdate {
	_u.mutation.ClearLeads()
	return _u
}

// RemoveLeadIDs removes the "leads" edge to Lead entities by IDs.
func (_u *TenantUpdate) RemoveLeadIDs(ids ...string) *TenantUpdate {
	_u.mutation.RemoveLeadIDs(ids...)
	return _u
}

// RemoveLeads removes "leads" edges to Lead entities.
func (_u *TenantUpdate) RemoveLeads(v ...*Lead) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeadIDs(ids...)
}

// ClearTradeIns clears all "trade_ins" edges to the TradeIn entity.
func (_u *TenantUpdate) ClearTradeIns() *TenantUpdate {
	_u.mutation.ClearTradeIns()
	return _u
}

// RemoveTradeInIDs removes the "trade_ins" edge to TradeIn entities by IDs.
func (_u *TenantUpdate) RemoveTradeInIDs(ids ...string) *TenantUpdate {
	_u.mutation.RemoveTradeInIDs(ids...)
	return _u
}

// RemoveTradeIns removes "trade_ins" edges to TradeIn entities.
func (_u *TenantUpdate) RemoveTradeIns(v ...*TradeIn) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTradeInIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *TenantUpdate) ClearNotifications() *TenantUpdate {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *TenantUpdate) RemoveNotificationIDs(ids ...string) *TenantUpdate {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *TenantUpdate) RemoveNotifications(v ...*Notification) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// ClearNotes clears all "notes" edges to the Note entity.
func (_u *TenantUpdate) ClearNotes() *TenantUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// RemoveNoteIDs removes the "notes" edge to Note entities by IDs.
func (_u *TenantUpdate) RemoveNoteIDs(ids ...string) *TenantUpdate {
	_u.mutation.RemoveNoteIDs(ids...)
	return _u
}

// RemoveNotes removes "notes" edges to Note entities.
func (_u *TenantUpdate) RemoveNotes(v ...*Note) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNoteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subdomain(); ok {
		if err := tenant.SubdomainValidator(v); err != nil {
			return &ValidationError{Name: "subdomain", err: fmt.Errorf(`ent: validator failed for field "Tenant.subdomain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingEmail(); ok {
		if err := tenant.BillingEmailValidator(v); err != nil {
			return &ValidationError{Name: "billing_email", err: fmt.Errorf(`ent: validator failed for field "Tenant.billing_email": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subdomain(); ok {
		_spec.SetField(tenant.FieldSubdomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Plan(); ok {
		_spec.SetField(tenant.FieldPlan, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(tenant.FieldSettings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.BillingEmail(); ok {
		_spec.SetField(tenant.FieldBillingEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionEndsAt(); ok {
		_spec.SetField(tenant.FieldSubscriptionEndsAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionEndsAtCleared() {
		_spec.ClearField(tenant.FieldSubscriptionEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CustomersTable,
			Columns: []string{tenant.CustomersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCustomersIDs(); len(nodes) > 0 && !_u.mutation.CustomersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CustomersTable,
			Columns: []string{tenant.CustomersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CustomersTable,
			Columns: []string{tenant.CustomersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VehiclesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.VehiclesTable,
			Columns: []string{tenant.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVehiclesIDs(); len(nodes) > 0 && !_u.mutation.VehiclesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.VehiclesTable,
			Columns: []string{tenant.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VehiclesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.VehiclesTable,
			Columns: []string{tenant.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DealsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DealsTable,
			Columns: []string{tenant.DealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDealsIDs(); len(nodes) > 0 && !_u.mutation.DealsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DealsTable,
			Columns: []string{tenant.DealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DealsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DealsTable,
			Columns: []string{tenant.DealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.LeadsTable,
			Columns: []string{tenant.LeadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeadsIDs(); len(nodes) > 0 && !_u.mutation.LeadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.LeadsTable,
			Columns: []string{tenant.LeadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.LeadsTable,
			Columns: []string{tenant.LeadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TradeInsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TradeInsTable,
			Columns: []string{tenant.TradeInsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradein.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTradeInsIDs(); len(nodes) > 0 && !_u.mutation.TradeInsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TradeInsTable,
			Columns: []string{tenant.TradeInsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradein.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TradeInsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TradeInsTable,
			Columns: []string{tenant.TradeInsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradein.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationsTable,
			Columns: []string{tenant.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationsTable,
			Columns: []string{tenant.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationsTable,
			Columns: []string{tenant.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotesTable,
			Columns: []string{tenant.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotesIDs(); len(nodes) > 0 && !_u.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotesTable,
			Columns: []string{tenant.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotesTable,
			Columns: []string{tenant.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubdomain sets the "subdomain" field.
func (_u *TenantUpdateOne) SetSubdomain(v string) *TenantUpdateOne {
	_u.mutation.SetSubdomain(v)
	return _u
}

// SetNillableSubdomain sets the "subdomain" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSubdomain(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetSubdomain(*v)
	}
	return _u
}

// SetPlan sets the "plan" field.
func (_u *TenantUpdateOne) SetPlan(v string) *TenantUpdateOne {
	_u.mutation.SetPlan(v)
	return _u
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillablePlan(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetPlan(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdateOne) SetStatus(v string) *TenantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableStatus(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettings sets the "settings" field.
func (_u *TenantUpdateOne) SetSettings(v map[string]interface{}) *TenantUpdateOne {
	_u.mutation.SetSettings(v)
	return _u
}

// SetBillingEmail sets the "billing_email" field.
func (_u *TenantUpdateOne) SetBillingEmail(v string) *TenantUpdateOne {
	_u.mutation.SetBillingEmail(v)
	return _u
}

// SetNillableBillingEmail sets the "billing_email" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableBillingEmail(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetBillingEmail(*v)
	}
	return _u
}

// SetSubscriptionEndsAt sets the "subscription_ends_at" field.
func (_u *TenantUpdateOne) SetSubscriptionEndsAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetSubscriptionEndsAt(v)
	return _u
}

// SetNillableSubscriptionEndsAt sets the "subscription_ends_at" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSubscriptionEndsAt(v *time.Time) *TenantUpdateOne {
	if v != nil {
		_u.SetSubscriptionEndsAt(*v)
	}
	return _u
}

// ClearSubscriptionEndsAt clears the value of the "subscription_ends_at" field.
func (_u *TenantUpdateOne) ClearSubscriptionEndsAt() *TenantUpdateOne {
	_u.mutation.ClearSubscriptionEndsAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdateOne) SetUpdatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *TenantUpdateOne) AddUserIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *TenantUpdateOne) AddUsers(v ...*User) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddCustomerIDs adds the "customers" edge to the Customer entity by IDs.
func (_u *TenantUpdateOne) AddCustomerIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.AddCustomerIDs(ids...)
	return _u
}

// AddCustomers adds the "customers" edges to the Customer entity.
func (_u *TenantUpdateOne) AddCustomers(v ...*Customer) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCustomerIDs(ids...)
}

// AddVehicleIDs adds the "vehicles" edge to the Vehicle entity by IDs.
func (_u *TenantUpdateOne) AddVehicleIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.AddVehicleIDs(ids...)
	return _u
}

// AddVehicles adds the "vehicles" edges to the Vehicle entity.
func (_u *TenantUpdateOne) AddVehicles(v ...*Vehicle) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVehicleIDs(ids...)
}

// AddDealIDs adds the "deals" edge to the Deal entity by IDs.
func (_u *TenantUpdateOne) AddDealIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.AddDealIDs(ids...)
	return _u
}

// AddDeals adds the "deals" edges to the Deal entity.
func (_u *TenantUpdateOne) AddDeals(v ...*Deal) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDealIDs(ids...)
}

// AddLeadIDs adds the "leads" edge to the Lead entity by IDs.
func (_u *TenantUpdateOne) AddLeadIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.AddLeadIDs(ids...)
	return _u
}

// AddLeads adds the "leads" edges to the Lead entity.
func (_u *TenantUpdateOne) AddLeads(v ...*Lead) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLeadIDs(ids...)
}

// AddTradeInIDs adds the "trade_ins" edge to the TradeIn entity by IDs.
func (_u *TenantUpdateOne) AddTradeInIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.AddTradeInIDs(ids...)
	return _u
}

// AddTradeIns adds the "trade_ins" edges to the TradeIn entity.
func (_u *TenantUpdateOne) AddTradeIns(v ...*TradeIn) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTradeInIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *TenantUpdateOne) AddNotificationIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *TenantUpdateOne) AddNotifications(v ...*Notification) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (_u *TenantUpdateOne) AddNoteIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.AddNoteIDs(ids...)
	return _u
}

// AddNotes adds the "notes" edges to the Note entity.
func (_u *TenantUpdateOne) AddNotes(v ...*Note) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNoteIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *TenantUpdateOne) ClearUsers() *TenantUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *TenantUpdateOne) RemoveUserIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *TenantUpdateOne) RemoveUsers(v ...*User) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearCustomers clears all "customers" edges to the Customer entity.
func (_u *TenantUpdateOne) ClearCustomers() *TenantUpdateOne {
	_u.mutation.ClearCustomers()
	return _u
}

// RemoveCustomerIDs removes the "customers" edge to Customer entities by IDs.
func (_u *TenantUpdateOne) RemoveCustomerIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.RemoveCustomerIDs(ids...)
	return _u
}

// RemoveCustomers removes "customers" edges to Customer entities.
func (_u *TenantUpdateOne) RemoveCustomers(v ...*Customer) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCustomerIDs(ids...)
}

// ClearVehicles clears all "vehicles" edges to the Vehicle entity.
func (_u *TenantUpdateOne) ClearVehicles() *TenantUpdateOne {
	_u.mutation.ClearVehicles()
	return _u
}

// RemoveVehicleIDs removes the "vehicles" edge to Vehicle entities by IDs.
func (_u *TenantUpdateOne) RemoveVehicleIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.RemoveVehicleIDs(ids...)
	return _u
}

// RemoveVehicles removes "vehicles" edges to Vehicle entities.
func (_u *TenantUpdateOne) RemoveVehicles(v ...*Vehicle) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVehicleIDs(ids...)
}

// ClearDeals clears all "deals" edges to the Deal entity.
func (_u *TenantUpdateOne) ClearDeals() *TenantUpdateOne {
	_u.mutation.ClearDeals()
	return _u
}

// RemoveDealIDs removes the "deals" edge to Deal entities by IDs.
func (_u *TenantUpdateOne) RemoveDealIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.RemoveDealIDs(ids...)
	return _u
}

// RemoveDeals removes "deals" edges to Deal entities.
func (_u *TenantUpdateOne) RemoveDeals(v ...*Deal) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDealIDs(ids...)
}

// ClearLeads clears all "leads" edges to the Lead entity.
func (_u *TenantUpdateOne) ClearLeads() *TenantUpdateOne {
	_u.mutation.ClearLeads()
	return _u
}

// RemoveLeadIDs removes the "leads" edge to Lead entities by IDs.
func (_u *TenantUpdateOne) RemoveLeadIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.RemoveLeadIDs(ids...)
	return _u
}

// RemoveLeads removes "leads" edges to Lead entities.
func (_u *TenantUpdateOne) RemoveLeads(v ...*Lead) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLeadIDs(ids...)
}

// ClearTradeIns clears all "trade_ins" edges to the TradeIn entity.
func (_u *TenantUpdateOne) ClearTradeIns() *TenantUpdateOne {
	_u.mutation.ClearTradeIns()
	return _u
}

// RemoveTradeInIDs removes the "trade_ins" edge to TradeIn entities by IDs.
func (_u *TenantUpdateOne) RemoveTradeInIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.RemoveTradeInIDs(ids...)
	return _u
}

// RemoveTradeIns removes "trade_ins" edges to TradeIn entities.
func (_u *TenantUpdateOne) RemoveTradeIns(v ...*TradeIn) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTradeInIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *TenantUpdateOne) ClearNotifications() *TenantUpdateOne {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *TenantUpdateOne) RemoveNotificationIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *TenantUpdateOne) RemoveNotifications(v ...*Notification) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// ClearNotes clears all "notes" edges to the Note entity.
func (_u *TenantUpdateOne) ClearNotes() *TenantUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// RemoveNoteIDs removes the "notes" edge to Note entities by IDs.
func (_u *TenantUpdateOne) RemoveNoteIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.RemoveNoteIDs(ids...)
	return _u
}

// RemoveNotes removes "notes" edges to Note entities.
func (_u *TenantUpdateOne) RemoveNotes(v ...*Note) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNoteIDs(ids...)
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subdomain(); ok {
		if err := tenant.SubdomainValidator(v); err != nil {
			return &ValidationError{Name: "subdomain", err: fmt.Errorf(`ent: validator failed for field "Tenant.subdomain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingEmail(); ok {
		if err := tenant.BillingEmailValidator(v); err != nil {
			return &ValidationError{Name: "billing_email", err: fmt.Errorf(`ent: validator failed for field "Tenant.billing_email": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subdomain(); ok {
		_spec.SetField(tenant.FieldSubdomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Plan(); ok {
		_spec.SetField(tenant.FieldPlan, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(tenant.FieldSettings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.BillingEmail(); ok {
		_spec.SetField(tenant.FieldBillingEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionEndsAt(); ok {
		_spec.SetField(tenant.FieldSubscriptionEndsAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionEndsAtCleared() {
		_spec.ClearField(tenant.FieldSubscriptionEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CustomersTable,
			Columns: []string{tenant.CustomersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCustomersIDs(); len(nodes) > 0 && !_u.mutation.CustomersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CustomersTable,
			Columns: []string{tenant.CustomersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.CustomersTable,
			Columns: []string{tenant.CustomersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VehiclesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.VehiclesTable,
			Columns: []string{tenant.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVehiclesIDs(); len(nodes) > 0 && !_u.mutation.VehiclesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.VehiclesTable,
			Columns: []string{tenant.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VehiclesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.VehiclesTable,
			Columns: []string{tenant.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DealsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DealsTable,
			Columns: []string{tenant.DealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDealsIDs(); len(nodes) > 0 && !_u.mutation.DealsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DealsTable,
			Columns: []string{tenant.DealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DealsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DealsTable,
			Columns: []string{tenant.DealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LeadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.LeadsTable,
			Columns: []string{tenant.LeadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLeadsIDs(); len(nodes) > 0 && !_u.mutation.LeadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.LeadsTable,
			Columns: []string{tenant.LeadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.LeadsTable,
			Columns: []string{tenant.LeadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lead.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TradeInsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TradeInsTable,
			Columns: []string{tenant.TradeInsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradein.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTradeInsIDs(); len(nodes) > 0 && !_u.mutation.TradeInsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TradeInsTable,
			Columns: []string{tenant.TradeInsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradein.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TradeInsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TradeInsTable,
			Columns: []string{tenant.TradeInsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradein.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationsTable,
			Columns: []string{tenant.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationsTable,
			Columns: []string{tenant.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationsTable,
			Columns: []string{tenant.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotesTable,
			Columns: []string{tenant.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotesIDs(); len(nodes) > 0 && !_u.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotesTable,
			Columns: []string{tenant.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotesTable,
			Columns: []string{tenant.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
