// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/autolytiq/backend/ent/tenant"
)

// Tenant is the model entity for the Tenant schema.
type Tenant struct {
	config `json:"-"`
	// ID of the ent.
	// Unique tenant identifier (CUID)
	ID string `json:"id,omitempty"`
	// Tenant organization name
	Name string `json:"name,omitempty"`
	// Unique subdomain for tenant
	Subdomain string `json:"subdomain,omitempty"`
	// Subscription plan: BASIC, PRO, ENTERPRISE
	Plan string `json:"plan,omitempty"`
	// Tenant status: ACTIVE, SUSPENDED, CANCELLED
	Status string `json:"status,omitempty"`
	// JSON configuration settings
	Settings map[string]interface{} `json:"settings,omitempty"`
	// Billing contact email
	BillingEmail string `json:"billing_email,omitempty"`
	// When subscription expires
	SubscriptionEndsAt *time.Time `json:"subscription_ends_at,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenantQuery when eager-loading is set.
	Edges        TenantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenantEdges holds the relations/edges for other nodes in the graph.
type TenantEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Customers holds the value of the customers edge.
	Customers []*Customer `json:"customers,omitempty"`
	// Vehicles holds the value of the vehicles edge.
	Vehicles []*Vehicle `json:"vehicles,omitempty"`
	// Deals holds the value of the deals edge.
	Deals []*Deal `json:"deals,omitempty"`
	// Leads holds the value of the leads edge.
	Leads []*Lead `json:"leads,omitempty"`
	// TradeIns holds the value of the trade_ins edge.
	TradeIns []*TradeIn `json:"trade_ins,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*Notification `json:"notifications,omitempty"`
	// Notes holds the value of the notes edge.
	Notes []*Note `json:"notes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// CustomersOrErr returns the Customers value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) CustomersOrErr() ([]*Customer, error) {
	if e.loadedTypes[1] {
		return e.Customers, nil
	}
	return nil, &NotLoadedError{edge: "customers"}
}

// VehiclesOrErr returns the Vehicles value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) VehiclesOrErr() ([]*Vehicle, error) {
	if e.loadedTypes[2] {
		return e.Vehicles, nil
	}
	return nil, &NotLoadedError{edge: "vehicles"}
}

// DealsOrErr returns the Deals value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) DealsOrErr() ([]*Deal, error) {
	if e.loadedTypes[3] {
		return e.Deals, nil
	}
	return nil, &NotLoadedError{edge: "deals"}
}

// LeadsOrErr returns the Leads value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) LeadsOrErr() ([]*Lead, error) {
	if e.loadedTypes[4] {
		return e.Leads, nil
	}
	return nil, &NotLoadedError{edge: "leads"}
}

// TradeInsOrErr returns the TradeIns value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) TradeInsOrErr() ([]*TradeIn, error) {
	if e.loadedTypes[5] {
		return e.TradeIns, nil
	}
	return nil, &NotLoadedError{edge: "trade_ins"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) NotificationsOrErr() ([]*Notification, error) {
	if e.loadedTypes[6] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// NotesOrErr returns the Notes value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) NotesOrErr() ([]*Note, error) {
	if e.loadedTypes[7] {
		return e.Notes, nil
	}
	return nil, &NotLoadedError{edge: "notes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tenant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenant.FieldSettings:
			values[i] = new([]byte)
		case tenant.FieldID, tenant.FieldName, tenant.FieldSubdomain, tenant.FieldPlan, tenant.FieldStatus, tenant.FieldBillingEmail:
			values[i] = new(sql.NullString)
		case tenant.FieldSubscriptionEndsAt, tenant.FieldCreatedAt, tenant.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tenant fields.
func (_m *Tenant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenant.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case tenant.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tenant.FieldSubdomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subdomain", values[i])
			} else if value.Valid {
				_m.Subdomain = value.String
			}
		case tenant.FieldPlan:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan", values[i])
			} else if value.Valid {
				_m.Plan = value.String
			}
		case tenant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case tenant.FieldSettings:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field settings", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Settings); err != nil {
					return fmt.Errorf("unmarshal field settings: %w", err)
				}
			}
		case tenant.FieldBillingEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_email", values[i])
			} else if value.Valid {
				_m.BillingEmail = value.String
			}
		case tenant.FieldSubscriptionEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_ends_at", values[i])
			} else if value.Valid {
				_m.SubscriptionEndsAt = new(time.Time)
				*_m.SubscriptionEndsAt = value.Time
			}
		case tenant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tenant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tenant.
// This includes values selected through modifiers, order, etc.
func (_m *Tenant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Tenant entity.
func (_m *Tenant) QueryUsers() *UserQuery {
	return NewTenantClient(_m.config).QueryUsers(_m)
}

// QueryCustomers queries the "customers" edge of the Tenant entity.
func (_m *Tenant) QueryCustomers() *CustomerQuery {
	return NewTenantClient(_m.config).QueryCustomers(_m)
}

// QueryVehicles queries the "vehicles" edge of the Tenant entity.
func (_m *Tenant) QueryVehicles() *VehicleQuery {
	return NewTenantClient(_m.config).QueryVehicles(_m)
}

// QueryDeals queries the "deals" edge of the Tenant entity.
func (_m *Tenant) QueryDeals() *DealQuery {
	return NewTenantClient(_m.config).QueryDeals(_m)
}

// QueryLeads queries the "leads" edge of the Tenant entity.
func (_m *Tenant) QueryLeads() *LeadQuery {
	return NewTenantClient(_m.config).QueryLeads(_m)
}

// QueryTradeIns queries the "trade_ins" edge of the Tenant entity.
func (_m *Tenant) QueryTradeIns() *TradeInQuery {
	return NewTenantClient(_m.config).QueryTradeIns(_m)
}

// QueryNotifications queries the "notifications" edge of the Tenant entity.
func (_m *Tenant) QueryNotifications() *NotificationQuery {
	return NewTenantClient(_m.config).QueryNotifications(_m)
}

// QueryNotes queries the "notes" edge of the Tenant entity.
func (_m *Tenant) QueryNotes() *NoteQuery {
	return NewTenantClient(_m.config).QueryNotes(_m)
}

// Update returns a builder for updating this Tenant.
// Note that you need to call Tenant.Unwrap() before calling this method if this Tenant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tenant) Update() *TenantUpdateOne {
	return NewTenantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tenant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tenant) Unwrap() *Tenant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tenant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tenant) String() string {
	var builder strings.Builder
	builder.WriteString("Tenant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("subdomain=")
	builder.WriteString(_m.Subdomain)
	builder.WriteString(", ")
	builder.WriteString("plan=")
	builder.WriteString(_m.Plan)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("settings=")
	builder.WriteString(fmt.Sprintf("%v", _m.Settings))
	builder.WriteString(", ")
	builder.WriteString("billing_email=")
	builder.WriteString(_m.BillingEmail)
	builder.WriteString(", ")
	if v := _m.SubscriptionEndsAt; v != nil {
		builder.WriteString("subscription_ends_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tenants is a parsable slice of Tenant.
type Tenants []*Tenant
