// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/autolytiq/backend/ent/customer"
	"github.com/autolytiq/backend/ent/deal"
	"github.com/autolytiq/backend/ent/predicate"
	"github.com/autolytiq/backend/ent/tenant"
	"github.com/autolytiq/backend/ent/tradein"
)

// TradeInUpdate is the builder for updating TradeIn entities.
type TradeInUpdate struct {
	config
	hooks    []Hook
	mutation *TradeInMutation
}

// Where appends a list predicates to the TradeInUpdate builder.
func (_u *TradeInUpdate) Where(ps ...predicate.TradeIn) *TradeInUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TradeInUpdate) SetTenantID(v string) *TradeInUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableTenantID(v *string) *TradeInUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetDealID sets the "deal_id" field.
func (_u *TradeInUpdate) SetDealID(v string) *TradeInUpdate {
	_u.mutation.SetDealID(v)
	return _u
}

// SetNillableDealID sets the "deal_id" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableDealID(v *string) *TradeInUpdate {
	if v != nil {
		_u.SetDealID(*v)
	}
	return _u
}

// ClearDealID clears the value of the "deal_id" field.
func (_u *TradeInUpdate) ClearDealID() *TradeInUpdate {
	_u.mutation.ClearDealID()
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *TradeInUpdate) SetCustomerID(v string) *TradeInUpdate {
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableCustomerID(v *string) *TradeInUpdate {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// ClearCustomerID clears the value of the "customer_id" field.
func (_u *TradeInUpdate) ClearCustomerID() *TradeInUpdate {
	_u.mutation.ClearCustomerID()
	return _u
}

// SetVin sets the "vin" field.
func (_u *TradeInUpdate) SetVin(v string) *TradeInUpdate {
	_u.mutation.SetVin(v)
	return _u
}

// SetNillableVin sets the "vin" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableVin(v *string) *TradeInUpdate {
	if v != nil {
		_u.SetVin(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *TradeInUpdate) SetYear(v int) *TradeInUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableYear(v *int) *TradeInUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *TradeInUpdate) AddYear(v int) *TradeInUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// SetMake sets the "make" field.
func (_u *TradeInUpdate) SetMake(v string) *TradeInUpdate {
	_u.mutation.SetMake(v)
	return _u
}

// SetNillableMake sets the "make" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableMake(v *string) *TradeInUpdate {
	if v != nil {
		_u.SetMake(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *TradeInUpdate) SetModel(v string) *TradeInUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableModel(v *string) *TradeInUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTrim sets the "trim" field.
func (_u *TradeInUpdate) SetTrim(v string) *TradeInUpdate {
	_u.mutation.SetTrim(v)
	return _u
}

// SetNillableTrim sets the "trim" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableTrim(v *string) *TradeInUpdate {
	if v != nil {
		_u.SetTrim(*v)
	}
	return _u
}

// ClearTrim clears the value of the "trim" field.
func (_u *TradeInUpdate) ClearTrim() *TradeInUpdate {
	_u.mutation.ClearTrim()
	return _u
}

// SetMileage sets the "mileage" field.
func (_u *TradeInUpdate) SetMileage(v int) *TradeInUpdate {
	_u.mutation.ResetMileage()
	_u.mutation.SetMileage(v)
	return _u
}

// SetNillableMileage sets the "mileage" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableMileage(v *int) *TradeInUpdate {
	if v != nil {
		_u.SetMileage(*v)
	}
	return _u
}

// AddMileage adds value to the "mileage" field.
func (_u *TradeInUpdate) AddMileage(v int) *TradeInUpdate {
	_u.mutation.AddMileage(v)
	return _u
}

// SetCondition sets the "condition" field.
func (_u *TradeInUpdate) SetCondition(v string) *TradeInUpdate {
	_u.mutation.SetCondition(v)
	return _u
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableCondition(v *string) *TradeInUpdate {
	if v != nil {
		_u.SetCondition(*v)
	}
	return _u
}

// ClearCondition clears the value of the "condition" field.
func (_u *TradeInUpdate) ClearCondition() *TradeInUpdate {
	_u.mutation.ClearCondition()
	return _u
}

// SetEstimatedValue sets the "estimated_value" field.
func (_u *TradeInUpdate) SetEstimatedValue(v int) *TradeInUpdate {
	_u.mutation.ResetEstimatedValue()
	_u.mutation.SetEstimatedValue(v)
	return _u
}

// SetNillableEstimatedValue sets the "estimated_value" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableEstimatedValue(v *int) *TradeInUpdate {
	if v != nil {
		_u.SetEstimatedValue(*v)
	}
	return _u
}

// AddEstimatedValue adds value to the "estimated_value" field.
func (_u *TradeInUpdate) AddEstimatedValue(v int) *TradeInUpdate {
	_u.mutation.AddEstimatedValue(v)
	return _u
}

// ClearEstimatedValue clears the value of the "estimated_value" field.
func (_u *TradeInUpdate) ClearEstimatedValue() *TradeInUpdate {
	_u.mutation.ClearEstimatedValue()
	return _u
}

// SetPayoffAmount sets the "payoff_amount" field.
func (_u *TradeInUpdate) SetPayoffAmount(v int) *TradeInUpdate {
	_u.mutation.ResetPayoffAmount()
	_u.mutation.SetPayoffAmount(v)
	return _u
}

// SetNillablePayoffAmount sets the "payoff_amount" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillablePayoffAmount(v *int) *TradeInUpdate {
	if v != nil {
		_u.SetPayoffAmount(*v)
	}
	return _u
}

// AddPayoffAmount adds value to the "payoff_amount" field.
func (_u *TradeInUpdate) AddPayoffAmount(v int) *TradeInUpdate {
	_u.mutation.AddPayoffAmount(v)
	return _u
}

// ClearPayoffAmount clears the value of the "payoff_amount" field.
func (_u *TradeInUpdate) ClearPayoffAmount() *TradeInUpdate {
	_u.mutation.ClearPayoffAmount()
	return _u
}

// SetActualCashValue sets the "actual_cash_value" field.
func (_u *TradeInUpdate) SetActualCashValue(v int) *TradeInUpdate {
	_u.mutation.ResetActualCashValue()
	_u.mutation.SetActualCashValue(v)
	return _u
}

// SetNillableActualCashValue sets the "actual_cash_value" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableActualCashValue(v *int) *TradeInUpdate {
	if v != nil {
		_u.SetActualCashValue(*v)
	}
	return _u
}

// AddActualCashValue adds value to the "actual_cash_value" field.
func (_u *TradeInUpdate) AddActualCashValue(v int) *TradeInUpdate {
	_u.mutation.AddActualCashValue(v)
	return _u
}

// ClearActualCashValue clears the value of the "actual_cash_value" field.
func (_u *TradeInUpdate) ClearActualCashValue() *TradeInUpdate {
	_u.mutation.ClearActualCashValue()
	return _u
}

// SetAllowance sets the "allowance" field.
func (_u *TradeInUpdate) SetAllowance(v int) *TradeInUpdate {
	_u.mutation.ResetAllowance()
	_u.mutation.SetAllowance(v)
	return _u
}

// SetNillableAllowance sets the "allowance" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableAllowance(v *int) *TradeInUpdate {
	if v != nil {
		_u.SetAllowance(*v)
	}
	return _u
}

// AddAllowance adds value to the "allowance" field.
func (_u *TradeInUpdate) AddAllowance(v int) *TradeInUpdate {
	_u.mutation.AddAllowance(v)
	return _u
}

// ClearAllowance clears the value of the "allowance" field.
func (_u *TradeInUpdate) ClearAllowance() *TradeInUpdate {
	_u.mutation.ClearAllowance()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TradeInUpdate) SetStatus(v string) *TradeInUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TradeInUpdate) SetNillableStatus(v *string) *TradeInUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TradeInUpdate) SetUpdatedAt(v time.Time) *TradeInUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TradeInUpdate) SetTenant(v *Tenant) *TradeInUpdate {
	return _u.SetTenantID(v.ID)
}

// SetDeal sets the "deal" edge to the Deal entity.
func (_u *TradeInUpdate) SetDeal(v *Deal) *TradeInUpdate {
	return _u.SetDealID(v.ID)
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_u *TradeInUpdate) SetCustomer(v *Customer) *TradeInUpdate {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the TradeInMutation object of the builder.
func (_u *TradeInUpdate) Mutation() *TradeInMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TradeInUpdate) ClearTenant() *TradeInUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearDeal clears the "deal" edge to the Deal entity.
func (_u *TradeInUpdate) ClearDeal() *TradeInUpdate {
	_u.mutation.ClearDeal()
	return _u
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (_u *TradeInUpdate) ClearCustomer() *TradeInUpdate {
	_u.mutation.ClearCustomer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TradeInUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TradeInUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TradeInUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TradeInUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TradeInUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tradein.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TradeInUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := tradein.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "TradeIn.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vin(); ok {
		if err := tradein.VinValidator(v); err != nil {
			return &ValidationError{Name: "vin", err: fmt.Errorf(`ent: validator failed for field "TradeIn.vin": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TradeIn.tenant"`)
	}
	return nil
}

func (_u *TradeInUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tradein.Table, tradein.Columns, sqlgraph.NewFieldSpec(tradein.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Vin(); ok {
		_spec.SetField(tradein.FieldVin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(tradein.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(tradein.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Make(); ok {
		_spec.SetField(tradein.FieldMake, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(tradein.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Trim(); ok {
		_spec.SetField(tradein.FieldTrim, field.TypeString, value)
	}
	if _u.mutation.TrimCleared() {
		_spec.ClearField(tradein.FieldTrim, field.TypeString)
	}
	if value, ok := _u.mutation.Mileage(); ok {
		_spec.SetField(tradein.FieldMileage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMileage(); ok {
		_spec.AddField(tradein.FieldMileage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(tradein.FieldCondition, field.TypeString, value)
	}
	if _u.mutation.ConditionCleared() {
		_spec.ClearField(tradein.FieldCondition, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedValue(); ok {
		_spec.SetField(tradein.FieldEstimatedValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedValue(); ok {
		_spec.AddField(tradein.FieldEstimatedValue, field.TypeInt, value)
	}
	if _u.mutation.EstimatedValueCleared() {
		_spec.ClearField(tradein.FieldEstimatedValue, field.TypeInt)
	}
	if value, ok := _u.mutation.PayoffAmount(); ok {
		_spec.SetField(tradein.FieldPayoffAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayoffAmount(); ok {
		_spec.AddField(tradein.FieldPayoffAmount, field.TypeInt, value)
	}
	if _u.mutation.PayoffAmountCleared() {
		_spec.ClearField(tradein.FieldPayoffAmount, field.TypeInt)
	}
	if value, ok := _u.mutation.ActualCashValue(); ok {
		_spec.SetField(tradein.FieldActualCashValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActualCashValue(); ok {
		_spec.AddField(tradein.FieldActualCashValue, field.TypeInt, value)
	}
	if _u.mutation.ActualCashValueCleared() {
		_spec.ClearField(tradein.FieldActualCashValue, field.TypeInt)
	}
	if value, ok := _u.mutation.Allowance(); ok {
		_spec.SetField(tradein.FieldAllowance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAllowance(); ok {
		_spec.AddField(tradein.FieldAllowance, field.TypeInt, value)
	}
	if _u.mutation.AllowanceCleared() {
		_spec.ClearField(tradein.FieldAllowance, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tradein.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tradein.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.TenantTable,
			Columns: []string{tradein.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.TenantTable,
			Columns: []string{tradein.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DealCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.DealTable,
			Columns: []string{tradein.DealColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DealIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.DealTable,
			Columns: []string{tradein.DealColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.CustomerTable,
			Columns: []string{tradein.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.CustomerTable,
			Columns: []string{tradein.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tradein.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TradeInUpdateOne is the builder for updating a single TradeIn entity.
type TradeInUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TradeInMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TradeInUpdateOne) SetTenantID(v string) *TradeInUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableTenantID(v *string) *TradeInUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetDealID sets the "deal_id" field.
func (_u *TradeInUpdateOne) SetDealID(v string) *TradeInUpdateOne {
	_u.mutation.SetDealID(v)
	return _u
}

// SetNillableDealID sets the "deal_id" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableDealID(v *string) *TradeInUpdateOne {
	if v != nil {
		_u.SetDealID(*v)
	}
	return _u
}

// ClearDealID clears the value of the "deal_id" field.
func (_u *TradeInUpdateOne) ClearDealID() *TradeInUpdateOne {
	_u.mutation.ClearDealID()
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *TradeInUpdateOne) SetCustomerID(v string) *TradeInUpdateOne {
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableCustomerID(v *string) *TradeInUpdateOne {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// ClearCustomerID clears the value of the "customer_id" field.
func (_u *TradeInUpdateOne) ClearCustomerID() *TradeInUpdateOne {
	_u.mutation.ClearCustomerID()
	return _u
}

// SetVin sets the "vin" field.
func (_u *TradeInUpdateOne) SetVin(v string) *TradeInUpdateOne {
	_u.mutation.SetVin(v)
	return _u
}

// SetNillableVin sets the "vin" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableVin(v *string) *TradeInUpdateOne {
	if v != nil {
		_u.SetVin(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *TradeInUpdateOne) SetYear(v int) *TradeInUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableYear(v *int) *TradeInUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *TradeInUpdateOne) AddYear(v int) *TradeInUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// SetMake sets the "make" field.
func (_u *TradeInUpdateOne) SetMake(v string) *TradeInUpdateOne {
	_u.mutation.SetMake(v)
	return _u
}

// SetNillableMake sets the "make" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableMake(v *string) *TradeInUpdateOne {
	if v != nil {
		_u.SetMake(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *TradeInUpdateOne) SetModel(v string) *TradeInUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableModel(v *string) *TradeInUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetTrim sets the "trim" field.
func (_u *TradeInUpdateOne) SetTrim(v string) *TradeInUpdateOne {
	_u.mutation.SetTrim(v)
	return _u
}

// SetNillableTrim sets the "trim" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableTrim(v *string) *TradeInUpdateOne {
	if v != nil {
		_u.SetTrim(*v)
	}
	return _u
}

// ClearTrim clears the value of the "trim" field.
func (_u *TradeInUpdateOne) ClearTrim() *TradeInUpdateOne {
	_u.mutation.ClearTrim()
	return _u
}

// SetMileage sets the "mileage" field.
func (_u *TradeInUpdateOne) SetMileage(v int) *TradeInUpdateOne {
	_u.mutation.ResetMileage()
	_u.mutation.SetMileage(v)
	return _u
}

// SetNillableMileage sets the "mileage" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableMileage(v *int) *TradeInUpdateOne {
	if v != nil {
		_u.SetMileage(*v)
	}
	return _u
}

// AddMileage adds value to the "mileage" field.
func (_u *TradeInUpdateOne) AddMileage(v int) *TradeInUpdateOne {
	_u.mutation.AddMileage(v)
	return _u
}

// SetCondition sets the "condition" field.
func (_u *TradeInUpdateOne) SetCondition(v string) *TradeInUpdateOne {
	_u.mutation.SetCondition(v)
	return _u
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableCondition(v *string) *TradeInUpdateOne {
	if v != nil {
		_u.SetCondition(*v)
	}
	return _u
}

// ClearCondition clears the value of the "condition" field.
func (_u *TradeInUpdateOne) ClearCondition() *TradeInUpdateOne {
	_u.mutation.ClearCondition()
	return _u
}

// SetEstimatedValue sets the "estimated_value" field.
func (_u *TradeInUpdateOne) SetEstimatedValue(v int) *TradeInUpdateOne {
	_u.mutation.ResetEstimatedValue()
	_u.mutation.SetEstimatedValue(v)
	return _u
}

// SetNillableEstimatedValue sets the "estimated_value" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableEstimatedValue(v *int) *TradeInUpdateOne {
	if v != nil {
		_u.SetEstimatedValue(*v)
	}
	return _u
}

// AddEstimatedValue adds value to the "estimated_value" field.
func (_u *TradeInUpdateOne) AddEstimatedValue(v int) *TradeInUpdateOne {
	_u.mutation.AddEstimatedValue(v)
	return _u
}

// ClearEstimatedValue clears the value of the "estimated_value" field.
func (_u *TradeInUpdateOne) ClearEstimatedValue() *TradeInUpdateOne {
	_u.mutation.ClearEstimatedValue()
	return _u
}

// SetPayoffAmount sets the "payoff_amount" field.
func (_u *TradeInUpdateOne) SetPayoffAmount(v int) *TradeInUpdateOne {
	_u.mutation.ResetPayoffAmount()
	_u.mutation.SetPayoffAmount(v)
	return _u
}

// SetNillablePayoffAmount sets the "payoff_amount" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillablePayoffAmount(v *int) *TradeInUpdateOne {
	if v != nil {
		_u.SetPayoffAmount(*v)
	}
	return _u
}

// AddPayoffAmount adds value to the "payoff_amount" field.
func (_u *TradeInUpdateOne) AddPayoffAmount(v int) *TradeInUpdateOne {
	_u.mutation.AddPayoffAmount(v)
	return _u
}

// ClearPayoffAmount clears the value of the "payoff_amount" field.
func (_u *TradeInUpdateOne) ClearPayoffAmount() *TradeInUpdateOne {
	_u.mutation.ClearPayoffAmount()
	return _u
}

// SetActualCashValue sets the "actual_cash_value" field.
func (_u *TradeInUpdateOne) SetActualCashValue(v int) *TradeInUpdateOne {
	_u.mutation.ResetActualCashValue()
	_u.mutation.SetActualCashValue(v)
	return _u
}

// SetNillableActualCashValue sets the "actual_cash_value" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableActualCashValue(v *int) *TradeInUpdateOne {
	if v != nil {
		_u.SetActualCashValue(*v)
	}
	return _u
}

// AddActualCashValue adds value to the "actual_cash_value" field.
func (_u *TradeInUpdateOne) AddActualCashValue(v int) *TradeInUpdateOne {
	_u.mutation.AddActualCashValue(v)
	return _u
}

// ClearActualCashValue clears the value of the "actual_cash_value" field.
func (_u *TradeInUpdateOne) ClearActualCashValue() *TradeInUpdateOne {
	_u.mutation.ClearActualCashValue()
	return _u
}

// SetAllowance sets the "allowance" field.
func (_u *TradeInUpdateOne) SetAllowance(v int) *TradeInUpdateOne {
	_u.mutation.ResetAllowance()
	_u.mutation.SetAllowance(v)
	return _u
}

// SetNillableAllowance sets the "allowance" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableAllowance(v *int) *TradeInUpdateOne {
	if v != nil {
		_u.SetAllowance(*v)
	}
	return _u
}

// AddAllowance adds value to the "allowance" field.
func (_u *TradeInUpdateOne) AddAllowance(v int) *TradeInUpdateOne {
	_u.mutation.AddAllowance(v)
	return _u
}

// ClearAllowance clears the value of the "allowance" field.
func (_u *TradeInUpdateOne) ClearAllowance() *TradeInUpdateOne {
	_u.mutation.ClearAllowance()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TradeInUpdateOne) SetStatus(v string) *TradeInUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TradeInUpdateOne) SetNillableStatus(v *string) *TradeInUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TradeInUpdateOne) SetUpdatedAt(v time.Time) *TradeInUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TradeInUpdateOne) SetTenant(v *Tenant) *TradeInUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetDeal sets the "deal" edge to the Deal entity.
func (_u *TradeInUpdateOne) SetDeal(v *Deal) *TradeInUpdateOne {
	return _u.SetDealID(v.ID)
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_u *TradeInUpdateOne) SetCustomer(v *Customer) *TradeInUpdateOne {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the TradeInMutation object of the builder.
func (_u *TradeInUpdateOne) Mutation() *TradeInMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TradeInUpdateOne) ClearTenant() *TradeInUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearDeal clears the "deal" edge to the Deal entity.
func (_u *TradeInUpdateOne) ClearDeal() *TradeInUpdateOne {
	_u.mutation.ClearDeal()
	return _u
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (_u *TradeInUpdateOne) ClearCustomer() *TradeInUpdateOne {
	_u.mutation.ClearCustomer()
	return _u
}

// Where appends a list predicates to the TradeInUpdate builder.
func (_u *TradeInUpdateOne) Where(ps ...predicate.TradeIn) *TradeInUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TradeInUpdateOne) Select(field string, fields ...string) *TradeInUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TradeIn entity.
func (_u *TradeInUpdateOne) Save(ctx context.Context) (*TradeIn, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TradeInUpdateOne) SaveX(ctx context.Context) *TradeIn {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TradeInUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TradeInUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TradeInUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tradein.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TradeInUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := tradein.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "TradeIn.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vin(); ok {
		if err := tradein.VinValidator(v); err != nil {
			return &ValidationError{Name: "vin", err: fmt.Errorf(`ent: validator failed for field "TradeIn.vin": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TradeIn.tenant"`)
	}
	return nil
}

func (_u *TradeInUpdateOne) sqlSave(ctx context.Context) (_node *TradeIn, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tradein.Table, tradein.Columns, sqlgraph.NewFieldSpec(tradein.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TradeIn.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tradein.FieldID)
		for _, f := range fields {
			if !tradein.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tradein.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Vin(); ok {
		_spec.SetField(tradein.FieldVin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(tradein.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(tradein.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Make(); ok {
		_spec.SetField(tradein.FieldMake, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(tradein.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Trim(); ok {
		_spec.SetField(tradein.FieldTrim, field.TypeString, value)
	}
	if _u.mutation.TrimCleared() {
		_spec.ClearField(tradein.FieldTrim, field.TypeString)
	}
	if value, ok := _u.mutation.Mileage(); ok {
		_spec.SetField(tradein.FieldMileage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMileage(); ok {
		_spec.AddField(tradein.FieldMileage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(tradein.FieldCondition, field.TypeString, value)
	}
	if _u.mutation.ConditionCleared() {
		_spec.ClearField(tradein.FieldCondition, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedValue(); ok {
		_spec.SetField(tradein.FieldEstimatedValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedValue(); ok {
		_spec.AddField(tradein.FieldEstimatedValue, field.TypeInt, value)
	}
	if _u.mutation.EstimatedValueCleared() {
		_spec.ClearField(tradein.FieldEstimatedValue, field.TypeInt)
	}
	if value, ok := _u.mutation.PayoffAmount(); ok {
		_spec.SetField(tradein.FieldPayoffAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayoffAmount(); ok {
		_spec.AddField(tradein.FieldPayoffAmount, field.TypeInt, value)
	}
	if _u.mutation.PayoffAmountCleared() {
		_spec.ClearField(tradein.FieldPayoffAmount, field.TypeInt)
	}
	if value, ok := _u.mutation.ActualCashValue(); ok {
		_spec.SetField(tradein.FieldActualCashValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActualCashValue(); ok {
		_spec.AddField(tradein.FieldActualCashValue, field.TypeInt, value)
	}
	if _u.mutation.ActualCashValueCleared() {
		_spec.ClearField(tradein.FieldActualCashValue, field.TypeInt)
	}
	if value, ok := _u.mutation.Allowance(); ok {
		_spec.SetField(tradein.FieldAllowance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAllowance(); ok {
		_spec.AddField(tradein.FieldAllowance, field.TypeInt, value)
	}
	if _u.mutation.AllowanceCleared() {
		_spec.ClearField(tradein.FieldAllowance, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tradein.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tradein.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.TenantTable,
			Columns: []string{tradein.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.TenantTable,
			Columns: []string{tradein.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DealCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.DealTable,
			Columns: []string{tradein.DealColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DealIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.DealTable,
			Columns: []string{tradein.DealColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.CustomerTable,
			Columns: []string{tradein.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.CustomerTable,
			Columns: []string{tradein.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TradeIn{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tradein.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
