// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/autolytiq/backend/ent/customer"
	"github.com/autolytiq/backend/ent/deal"
	"github.com/autolytiq/backend/ent/tenant"
	"github.com/autolytiq/backend/ent/tradein"
)

// TradeInCreate is the builder for creating a TradeIn entity.
type TradeInCreate struct {
	config
	mutation *TradeInMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *TradeInCreate) SetTenantID(v string) *TradeInCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetDealID sets the "deal_id" field.
func (_c *TradeInCreate) SetDealID(v string) *TradeInCreate {
	_c.mutation.SetDealID(v)
	return _c
}

// SetNillableDealID sets the "deal_id" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableDealID(v *string) *TradeInCreate {
	if v != nil {
		_c.SetDealID(*v)
	}
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *TradeInCreate) SetCustomerID(v string) *TradeInCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableCustomerID(v *string) *TradeInCreate {
	if v != nil {
		_c.SetCustomerID(*v)
	}
	return _c
}

// SetVin sets the "vin" field.
func (_c *TradeInCreate) SetVin(v string) *TradeInCreate {
	_c.mutation.SetVin(v)
	return _c
}

// SetYear sets the "year" field.
func (_c *TradeInCreate) SetYear(v int) *TradeInCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetMake sets the "make" field.
func (_c *TradeInCreate) SetMake(v string) *TradeInCreate {
	_c.mutation.SetMake(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *TradeInCreate) SetModel(v string) *TradeInCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetTrim sets the "trim" field.
func (_c *TradeInCreate) SetTrim(v string) *TradeInCreate {
	_c.mutation.SetTrim(v)
	return _c
}

// SetNillableTrim sets the "trim" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableTrim(v *string) *TradeInCreate {
	if v != nil {
		_c.SetTrim(*v)
	}
	return _c
}

// SetMileage sets the "mileage" field.
func (_c *TradeInCreate) SetMileage(v int) *TradeInCreate {
	_c.mutation.SetMileage(v)
	return _c
}

// SetCondition sets the "condition" field.
func (_c *TradeInCreate) SetCondition(v string) *TradeInCreate {
	_c.mutation.SetCondition(v)
	return _c
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableCondition(v *string) *TradeInCreate {
	if v != nil {
		_c.SetCondition(*v)
	}
	return _c
}

// SetEstimatedValue sets the "estimated_value" field.
func (_c *TradeInCreate) SetEstimatedValue(v int) *TradeInCreate {
	_c.mutation.SetEstimatedValue(v)
	return _c
}

// SetNillableEstimatedValue sets the "estimated_value" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableEstimatedValue(v *int) *TradeInCreate {
	if v != nil {
		_c.SetEstimatedValue(*v)
	}
	return _c
}

// SetPayoffAmount sets the "payoff_amount" field.
func (_c *TradeInCreate) SetPayoffAmount(v int) *TradeInCreate {
	_c.mutation.SetPayoffAmount(v)
	return _c
}

// SetNillablePayoffAmount sets the "payoff_amount" field if the given value is not nil.
func (_c *TradeInCreate) SetNillablePayoffAmount(v *int) *TradeInCreate {
	if v != nil {
		_c.SetPayoffAmount(*v)
	}
	return _c
}

// SetActualCashValue sets the "actual_cash_value" field.
func (_c *TradeInCreate) SetActualCashValue(v int) *TradeInCreate {
	_c.mutation.SetActualCashValue(v)
	return _c
}

// SetNillableActualCashValue sets the "actual_cash_value" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableActualCashValue(v *int) *TradeInCreate {
	if v != nil {
		_c.SetActualCashValue(*v)
	}
	return _c
}

// SetAllowance sets the "allowance" field.
func (_c *TradeInCreate) SetAllowance(v int) *TradeInCreate {
	_c.mutation.SetAllowance(v)
	return _c
}

// SetNillableAllowance sets the "allowance" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableAllowance(v *int) *TradeInCreate {
	if v != nil {
		_c.SetAllowance(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TradeInCreate) SetStatus(v string) *TradeInCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableStatus(v *string) *TradeInCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TradeInCreate) SetCreatedAt(v time.Time) *TradeInCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableCreatedAt(v *time.Time) *TradeInCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TradeInCreate) SetUpdatedAt(v time.Time) *TradeInCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TradeInCreate) SetNillableUpdatedAt(v *time.Time) *TradeInCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TradeInCreate) SetID(v string) *TradeInCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *TradeInCreate) SetTenant(v *Tenant) *TradeInCreate {
	return _c.SetTenantID(v.ID)
}

// SetDeal sets the "deal" edge to the Deal entity.
func (_c *TradeInCreate) SetDeal(v *Deal) *TradeInCreate {
	return _c.SetDealID(v.ID)
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_c *TradeInCreate) SetCustomer(v *Customer) *TradeInCreate {
	return _c.SetCustomerID(v.ID)
}

// Mutation returns the TradeInMutation object of the builder.
func (_c *TradeInCreate) Mutation() *TradeInMutation {
	return _c.mutation
}

// Save creates the TradeIn in the database.
func (_c *TradeInCreate) Save(ctx context.Context) (*TradeIn, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TradeInCreate) SaveX(ctx context.Context) *TradeIn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TradeInCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TradeInCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TradeInCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := tradein.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tradein.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tradein.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TradeInCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TradeIn.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := tradein.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "TradeIn.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Vin(); !ok {
		return &ValidationError{Name: "vin", err: errors.New(`ent: missing required field "TradeIn.vin"`)}
	}
	if v, ok := _c.mutation.Vin(); ok {
		if err := tradein.VinValidator(v); err != nil {
			return &ValidationError{Name: "vin", err: fmt.Errorf(`ent: validator failed for field "TradeIn.vin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "TradeIn.year"`)}
	}
	if _, ok := _c.mutation.Make(); !ok {
		return &ValidationError{Name: "make", err: errors.New(`ent: missing required field "TradeIn.make"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "TradeIn.model"`)}
	}
	if _, ok := _c.mutation.Mileage(); !ok {
		return &ValidationError{Name: "mileage", err: errors.New(`ent: missing required field "TradeIn.mileage"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TradeIn.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TradeIn.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TradeIn.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "TradeIn.tenant"`)}
	}
	return nil
}

func (_c *TradeInCreate) sqlSave(ctx context.Context) (*TradeIn, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TradeIn.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TradeInCreate) createSpec() (*TradeIn, *sqlgraph.CreateSpec) {
	var (
		_node = &TradeIn{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tradein.Table, sqlgraph.NewFieldSpec(tradein.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Vin(); ok {
		_spec.SetField(tradein.FieldVin, field.TypeString, value)
		_node.Vin = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(tradein.FieldYear, field.TypeInt, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.Make(); ok {
		_spec.SetField(tradein.FieldMake, field.TypeString, value)
		_node.Make = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(tradein.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Trim(); ok {
		_spec.SetField(tradein.FieldTrim, field.TypeString, value)
		_node.Trim = &value
	}
	if value, ok := _c.mutation.Mileage(); ok {
		_spec.SetField(tradein.FieldMileage, field.TypeInt, value)
		_node.Mileage = value
	}
	if value, ok := _c.mutation.Condition(); ok {
		_spec.SetField(tradein.FieldCondition, field.TypeString, value)
		_node.Condition = &value
	}
	if value, ok := _c.mutation.EstimatedValue(); ok {
		_spec.SetField(tradein.FieldEstimatedValue, field.TypeInt, value)
		_node.EstimatedValue = &value
	}
	if value, ok := _c.mutation.PayoffAmount(); ok {
		_spec.SetField(tradein.FieldPayoffAmount, field.TypeInt, value)
		_node.PayoffAmount = &value
	}
	if value, ok := _c.mutation.ActualCashValue(); ok {
		_spec.SetField(tradein.FieldActualCashValue, field.TypeInt, value)
		_node.ActualCashValue = &value
	}
	if value, ok := _c.mutation.Allowance(); ok {
		_spec.SetField(tradein.FieldAllowance, field.TypeInt, value)
		_node.Allowance = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tradein.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tradein.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tradein.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.TenantTable,
			Columns: []string{tradein.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DealIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.DealTable,
			Columns: []string{tradein.DealColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DealID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradein.CustomerTable,
			Columns: []string{tradein.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomerID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TradeInCreateBulk is the builder for creating many TradeIn entities in bulk.
type TradeInCreateBulk struct {
	config
	err      error
	builders []*TradeInCreate
}

// Save creates the TradeIn entities in the database.
func (_c *TradeInCreateBulk) Save(ctx context.Context) ([]*TradeIn, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TradeIn, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TradeInMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TradeInCreateBulk) SaveX(ctx context.Context) []*TradeIn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TradeInCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TradeInCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
