// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/autolytiq/backend/ent/customer"
	"github.com/autolytiq/backend/ent/deal"
	"github.com/autolytiq/backend/ent/tenant"
	"github.com/autolytiq/backend/ent/tradein"
)

// TradeIn is the model entity for the TradeIn schema.
type TradeIn struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// DealID holds the value of the "deal_id" field.
	DealID *string `json:"deal_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID *string `json:"customer_id,omitempty"`
	// Vin holds the value of the "vin" field.
	Vin string `json:"vin,omitempty"`
	// Year holds the value of the "year" field.
	Year int `json:"year,omitempty"`
	// Make holds the value of the "make" field.
	Make string `json:"make,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Trim holds the value of the "trim" field.
	Trim *string `json:"trim,omitempty"`
	// Mileage holds the value of the "mileage" field.
	Mileage int `json:"mileage,omitempty"`
	// Condition holds the value of the "condition" field.
	Condition *string `json:"condition,omitempty"`
	// EstimatedValue holds the value of the "estimated_value" field.
	EstimatedValue *int `json:"estimated_value,omitempty"`
	// PayoffAmount holds the value of the "payoff_amount" field.
	PayoffAmount *int `json:"payoff_amount,omitempty"`
	// ActualCashValue holds the value of the "actual_cash_value" field.
	ActualCashValue *int `json:"actual_cash_value,omitempty"`
	// Allowance holds the value of the "allowance" field.
	Allowance *int `json:"allowance,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TradeInQuery when eager-loading is set.
	Edges        TradeInEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TradeInEdges holds the relations/edges for other nodes in the graph.
type TradeInEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Deal holds the value of the deal edge.
	Deal *Deal `json:"deal,omitempty"`
	// Customer holds the value of the customer edge.
	Customer *Customer `json:"customer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TradeInEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// DealOrErr returns the Deal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TradeInEdges) DealOrErr() (*Deal, error) {
	if e.Deal != nil {
		return e.Deal, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: deal.Label}
	}
	return nil, &NotLoadedError{edge: "deal"}
}

// CustomerOrErr returns the Customer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TradeInEdges) CustomerOrErr() (*Customer, error) {
	if e.Customer != nil {
		return e.Customer, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: customer.Label}
	}
	return nil, &NotLoadedError{edge: "customer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TradeIn) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tradein.FieldYear, tradein.FieldMileage, tradein.FieldEstimatedValue, tradein.FieldPayoffAmount, tradein.FieldActualCashValue, tradein.FieldAllowance:
			values[i] = new(sql.NullInt64)
		case tradein.FieldID, tradein.FieldTenantID, tradein.FieldDealID, tradein.FieldCustomerID, tradein.FieldVin, tradein.FieldMake, tradein.FieldModel, tradein.FieldTrim, tradein.FieldCondition, tradein.FieldStatus:
			values[i] = new(sql.NullString)
		case tradein.FieldCreatedAt, tradein.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TradeIn fields.
func (_m *TradeIn) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tradein.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case tradein.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case tradein.FieldDealID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deal_id", values[i])
			} else if value.Valid {
				_m.DealID = new(string)
				*_m.DealID = value.String
			}
		case tradein.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				_m.CustomerID = new(string)
				*_m.CustomerID = value.String
			}
		case tradein.FieldVin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vin", values[i])
			} else if value.Valid {
				_m.Vin = value.String
			}
		case tradein.FieldYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year", values[i])
			} else if value.Valid {
				_m.Year = int(value.Int64)
			}
		case tradein.FieldMake:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field make", values[i])
			} else if value.Valid {
				_m.Make = value.String
			}
		case tradein.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case tradein.FieldTrim:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trim", values[i])
			} else if value.Valid {
				_m.Trim = new(string)
				*_m.Trim = value.String
			}
		case tradein.FieldMileage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mileage", values[i])
			} else if value.Valid {
				_m.Mileage = int(value.Int64)
			}
		case tradein.FieldCondition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field condition", values[i])
			} else if value.Valid {
				_m.Condition = new(string)
				*_m.Condition = value.String
			}
		case tradein.FieldEstimatedValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_value", values[i])
			} else if value.Valid {
				_m.EstimatedValue = new(int)
				*_m.EstimatedValue = int(value.Int64)
			}
		case tradein.FieldPayoffAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payoff_amount", values[i])
			} else if value.Valid {
				_m.PayoffAmount = new(int)
				*_m.PayoffAmount = int(value.Int64)
			}
		case tradein.FieldActualCashValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cash_value", values[i])
			} else if value.Valid {
				_m.ActualCashValue = new(int)
				*_m.ActualCashValue = int(value.Int64)
			}
		case tradein.FieldAllowance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field allowance", values[i])
			} else if value.Valid {
				_m.Allowance = new(int)
				*_m.Allowance = int(value.Int64)
			}
		case tradein.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case tradein.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tradein.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TradeIn.
// This includes values selected through modifiers, order, etc.
func (_m *TradeIn) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the TradeIn entity.
func (_m *TradeIn) QueryTenant() *TenantQuery {
	return NewTradeInClient(_m.config).QueryTenant(_m)
}

// QueryDeal queries the "deal" edge of the TradeIn entity.
func (_m *TradeIn) QueryDeal() *DealQuery {
	return NewTradeInClient(_m.config).QueryDeal(_m)
}

// QueryCustomer queries the "customer" edge of the TradeIn entity.
func (_m *TradeIn) QueryCustomer() *CustomerQuery {
	return NewTradeInClient(_m.config).QueryCustomer(_m)
}

// Update returns a builder for updating this TradeIn.
// Note that you need to call TradeIn.Unwrap() before calling this method if this TradeIn
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TradeIn) Update() *TradeInUpdateOne {
	return NewTradeInClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TradeIn entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TradeIn) Unwrap() *TradeIn {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TradeIn is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TradeIn) String() string {
	var builder strings.Builder
	builder.WriteString("TradeIn(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	if v := _m.DealID; v != nil {
		builder.WriteString("deal_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CustomerID; v != nil {
		builder.WriteString("customer_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("vin=")
	builder.WriteString(_m.Vin)
	builder.WriteString(", ")
	builder.WriteString("year=")
	builder.WriteString(fmt.Sprintf("%v", _m.Year))
	builder.WriteString(", ")
	builder.WriteString("make=")
	builder.WriteString(_m.Make)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	if v := _m.Trim; v != nil {
		builder.WriteString("trim=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("mileage=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mileage))
	builder.WriteString(", ")
	if v := _m.Condition; v != nil {
		builder.WriteString("condition=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.EstimatedValue; v != nil {
		builder.WriteString("estimated_value=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PayoffAmount; v != nil {
		builder.WriteString("payoff_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActualCashValue; v != nil {
		builder.WriteString("actual_cash_value=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Allowance; v != nil {
		builder.WriteString("allowance=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TradeIns is a parsable slice of TradeIn.
type TradeIns []*TradeIn
