// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/autolytiq/backend/ent/tenant"
	"github.com/autolytiq/backend/ent/vehicle"
)

// Vehicle is the model entity for the Vehicle schema.
type Vehicle struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Vin holds the value of the "vin" field.
	Vin string `json:"vin,omitempty"`
	// Year holds the value of the "year" field.
	Year int `json:"year,omitempty"`
	// Make holds the value of the "make" field.
	Make string `json:"make,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Trim holds the value of the "trim" field.
	Trim *string `json:"trim,omitempty"`
	// Mileage holds the value of the "mileage" field.
	Mileage int `json:"mileage,omitempty"`
	// StockNumber holds the value of the "stock_number" field.
	StockNumber *string `json:"stock_number,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Cost holds the value of the "cost" field.
	Cost *int `json:"cost,omitempty"`
	// MarketPrice holds the value of the "market_price" field.
	MarketPrice *int `json:"market_price,omitempty"`
	// AskingPrice holds the value of the "asking_price" field.
	AskingPrice *int `json:"asking_price,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VehicleQuery when eager-loading is set.
	Edges        VehicleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VehicleEdges holds the relations/edges for other nodes in the graph.
type VehicleEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Deals holds the value of the deals edge.
	Deals []*Deal `json:"deals,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VehicleEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// DealsOrErr returns the Deals value or an error if the edge
// was not loaded in eager-loading.
func (e VehicleEdges) DealsOrErr() ([]*Deal, error) {
	if e.loadedTypes[1] {
		return e.Deals, nil
	}
	return nil, &NotLoadedError{edge: "deals"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Vehicle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vehicle.FieldYear, vehicle.FieldMileage, vehicle.FieldCost, vehicle.FieldMarketPrice, vehicle.FieldAskingPrice:
			values[i] = new(sql.NullInt64)
		case vehicle.FieldID, vehicle.FieldTenantID, vehicle.FieldVin, vehicle.FieldMake, vehicle.FieldModel, vehicle.FieldTrim, vehicle.FieldStockNumber, vehicle.FieldStatus:
			values[i] = new(sql.NullString)
		case vehicle.FieldCreatedAt, vehicle.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Vehicle fields.
func (_m *Vehicle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vehicle.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case vehicle.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case vehicle.FieldVin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vin", values[i])
			} else if value.Valid {
				_m.Vin = value.String
			}
		case vehicle.FieldYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year", values[i])
			} else if value.Valid {
				_m.Year = int(value.Int64)
			}
		case vehicle.FieldMake:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field make", values[i])
			} else if value.Valid {
				_m.Make = value.String
			}
		case vehicle.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case vehicle.FieldTrim:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trim", values[i])
			} else if value.Valid {
				_m.Trim = new(string)
				*_m.Trim = value.String
			}
		case vehicle.FieldMileage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mileage", values[i])
			} else if value.Valid {
				_m.Mileage = int(value.Int64)
			}
		case vehicle.FieldStockNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stock_number", values[i])
			} else if value.Valid {
				_m.StockNumber = new(string)
				*_m.StockNumber = value.String
			}
		case vehicle.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case vehicle.FieldCost:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost", values[i])
			} else if value.Valid {
				_m.Cost = new(int)
				*_m.Cost = int(value.Int64)
			}
		case vehicle.FieldMarketPrice:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field market_price", values[i])
			} else if value.Valid {
				_m.MarketPrice = new(int)
				*_m.MarketPrice = int(value.Int64)
			}
		case vehicle.FieldAskingPrice:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field asking_price", values[i])
			} else if value.Valid {
				_m.AskingPrice = new(int)
				*_m.AskingPrice = int(value.Int64)
			}
		case vehicle.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case vehicle.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Vehicle.
// This includes values selected through modifiers, order, etc.
func (_m *Vehicle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Vehicle entity.
func (_m *Vehicle) QueryTenant() *TenantQuery {
	return NewVehicleClient(_m.config).QueryTenant(_m)
}

// QueryDeals queries the "deals" edge of the Vehicle entity.
func (_m *Vehicle) QueryDeals() *DealQuery {
	return NewVehicleClient(_m.config).QueryDeals(_m)
}

// Update returns a builder for updating this Vehicle.
// Note that you need to call Vehicle.Unwrap() before calling this method if this Vehicle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Vehicle) Update() *VehicleUpdateOne {
	return NewVehicleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Vehicle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Vehicle) Unwrap() *Vehicle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Vehicle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Vehicle) String() string {
	var builder strings.Builder
	builder.WriteString("Vehicle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("vin=")
	builder.WriteString(_m.Vin)
	builder.WriteString(", ")
	builder.WriteString("year=")
	builder.WriteString(fmt.Sprintf("%v", _m.Year))
	builder.WriteString(", ")
	builder.WriteString("make=")
	builder.WriteString(_m.Make)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	if v := _m.Trim; v != nil {
		builder.WriteString("trim=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("mileage=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mileage))
	builder.WriteString(", ")
	if v := _m.StockNumber; v != nil {
		builder.WriteString("stock_number=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Cost; v != nil {
		builder.WriteString("cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MarketPrice; v != nil {
		builder.WriteString("market_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AskingPrice; v != nil {
		builder.WriteString("asking_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Vehicles is a parsable slice of Vehicle.
type Vehicles []*Vehicle
