// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/autolytiq/backend/ent/deal"
	"github.com/autolytiq/backend/ent/tenant"
	"github.com/autolytiq/backend/ent/vehicle"
)

// VehicleCreate is the builder for creating a Vehicle entity.
type VehicleCreate struct {
	config
	mutation *VehicleMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *VehicleCreate) SetTenantID(v string) *VehicleCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetVin sets the "vin" field.
func (_c *VehicleCreate) SetVin(v string) *VehicleCreate {
	_c.mutation.SetVin(v)
	return _c
}

// SetYear sets the "year" field.
func (_c *VehicleCreate) SetYear(v int) *VehicleCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetMake sets the "make" field.
func (_c *VehicleCreate) SetMake(v string) *VehicleCreate {
	_c.mutation.SetMake(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *VehicleCreate) SetModel(v string) *VehicleCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetTrim sets the "trim" field.
func (_c *VehicleCreate) SetTrim(v string) *VehicleCreate {
	_c.mutation.SetTrim(v)
	return _c
}

// SetNillableTrim sets the "trim" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableTrim(v *string) *VehicleCreate {
	if v != nil {
		_c.SetTrim(*v)
	}
	return _c
}

// SetMileage sets the "mileage" field.
func (_c *VehicleCreate) SetMileage(v int) *VehicleCreate {
	_c.mutation.SetMileage(v)
	return _c
}

// SetStockNumber sets the "stock_number" field.
func (_c *VehicleCreate) SetStockNumber(v string) *VehicleCreate {
	_c.mutation.SetStockNumber(v)
	return _c
}

// SetNillableStockNumber sets the "stock_number" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableStockNumber(v *string) *VehicleCreate {
	if v != nil {
		_c.SetStockNumber(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *VehicleCreate) SetStatus(v string) *VehicleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableStatus(v *string) *VehicleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *VehicleCreate) SetCost(v int) *VehicleCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableCost(v *int) *VehicleCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetMarketPrice sets the "market_price" field.
func (_c *VehicleCreate) SetMarketPrice(v int) *VehicleCreate {
	_c.mutation.SetMarketPrice(v)
	return _c
}

// SetNillableMarketPrice sets the "market_price" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableMarketPrice(v *int) *VehicleCreate {
	if v != nil {
		_c.SetMarketPrice(*v)
	}
	return _c
}

// SetAskingPrice sets the "asking_price" field.
func (_c *VehicleCreate) SetAskingPrice(v int) *VehicleCreate {
	_c.mutation.SetAskingPrice(v)
	return _c
}

// SetNillableAskingPrice sets the "asking_price" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableAskingPrice(v *int) *VehicleCreate {
	if v != nil {
		_c.SetAskingPrice(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VehicleCreate) SetCreatedAt(v time.Time) *VehicleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableCreatedAt(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VehicleCreate) SetUpdatedAt(v time.Time) *VehicleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableUpdatedAt(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VehicleCreate) SetID(v string) *VehicleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *VehicleCreate) SetTenant(v *Tenant) *VehicleCreate {
	return _c.SetTenantID(v.ID)
}

// AddDealIDs adds the "deals" edge to the Deal entity by IDs.
func (_c *VehicleCreate) AddDealIDs(ids ...string) *VehicleCreate {
	_c.mutation.AddDealIDs(ids...)
	return _c
}

// AddDeals adds the "deals" edges to the Deal entity.
func (_c *VehicleCreate) AddDeals(v ...*Deal) *VehicleCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDealIDs(ids...)
}

// Mutation returns the VehicleMutation object of the builder.
func (_c *VehicleCreate) Mutation() *VehicleMutation {
	return _c.mutation
}

// Save creates the Vehicle in the database.
func (_c *VehicleCreate) Save(ctx context.Context) (*Vehicle, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VehicleCreate) SaveX(ctx context.Context) *Vehicle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VehicleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VehicleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VehicleCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := vehicle.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vehicle.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := vehicle.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VehicleCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Vehicle.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := vehicle.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Vehicle.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Vin(); !ok {
		return &ValidationError{Name: "vin", err: errors.New(`ent: missing required field "Vehicle.vin"`)}
	}
	if v, ok := _c.mutation.Vin(); ok {
		if err := vehicle.VinValidator(v); err != nil {
			return &ValidationError{Name: "vin", err: fmt.Errorf(`ent: validator failed for field "Vehicle.vin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "Vehicle.year"`)}
	}
	if _, ok := _c.mutation.Make(); !ok {
		return &ValidationError{Name: "make", err: errors.New(`ent: missing required field "Vehicle.make"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "Vehicle.model"`)}
	}
	if _, ok := _c.mutation.Mileage(); !ok {
		return &ValidationError{Name: "mileage", err: errors.New(`ent: missing required field "Vehicle.mileage"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Vehicle.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Vehicle.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Vehicle.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Vehicle.tenant"`)}
	}
	return nil
}

func (_c *VehicleCreate) sqlSave(ctx context.Context) (*Vehicle, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Vehicle.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VehicleCreate) createSpec() (*Vehicle, *sqlgraph.CreateSpec) {
	var (
		_node = &Vehicle{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vehicle.Table, sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Vin(); ok {
		_spec.SetField(vehicle.FieldVin, field.TypeString, value)
		_node.Vin = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(vehicle.FieldYear, field.TypeInt, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.Make(); ok {
		_spec.SetField(vehicle.FieldMake, field.TypeString, value)
		_node.Make = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(vehicle.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Trim(); ok {
		_spec.SetField(vehicle.FieldTrim, field.TypeString, value)
		_node.Trim = &value
	}
	if value, ok := _c.mutation.Mileage(); ok {
		_spec.SetField(vehicle.FieldMileage, field.TypeInt, value)
		_node.Mileage = value
	}
	if value, ok := _c.mutation.StockNumber(); ok {
		_spec.SetField(vehicle.FieldStockNumber, field.TypeString, value)
		_node.StockNumber = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(vehicle.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(vehicle.FieldCost, field.TypeInt, value)
		_node.Cost = &value
	}
	if value, ok := _c.mutation.MarketPrice(); ok {
		_spec.SetField(vehicle.FieldMarketPrice, field.TypeInt, value)
		_node.MarketPrice = &value
	}
	if value, ok := _c.mutation.AskingPrice(); ok {
		_spec.SetField(vehicle.FieldAskingPrice, field.TypeInt, value)
		_node.AskingPrice = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vehicle.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vehicle.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vehicle.TenantTable,
			Columns: []string{vehicle.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DealsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vehicle.DealsTable,
			Columns: []string{vehicle.DealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VehicleCreateBulk is the builder for creating many Vehicle entities in bulk.
type VehicleCreateBulk struct {
	config
	err      error
	builders []*VehicleCreate
}

// Save creates the Vehicle entities in the database.
func (_c *VehicleCreateBulk) Save(ctx context.Context) ([]*Vehicle, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Vehicle, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VehicleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VehicleCreateBulk) SaveX(ctx context.Context) []*Vehicle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VehicleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VehicleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
