apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: autolytiq-dev
type: Opaque
stringData:
  DATABASE_URL: postgresql://autolytiq:autolytiq@autolytiq-postgres.autolytiq-dev.svc.cluster.local:5432/autolytiq
  JWT_PUBLIC_KEY: |-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApGfG60JgB+vHNiTNGOBy
    g4S1hoPazTA/gkGEXUXMaLLq5yRvCNrI6VOGGAaHo9dZYkTfGZNVVRFl1kYyqS/f
    wLw1sYUNsGrD+VUKPTySGTsNMndvrYVF/1DdbC+aD7agEXkNKOxPQ0PqSxkbZVqM
    l8I4JVXu2fLG3gNsYch0JJYRqpMfrQa6RlmKCNt2uQ6Xo8XzYx+lNEzbG8VS9/6g
    xF2Y2v3hF8oD7YVOlJawVSjGInxjeRGna43EIBgzHuLlHotE5T7V6czS4QhIwTZY
    h9+VFeReyqYhB1tZEDQhTWZ+9VtxxvpG6vE11wV8L19/9ey7NwxKXlzVEk+iXdc5
    FQIDAQAB
    -----END PUBLIC KEY-----
  JWT_ISSUER: autolytiq-dev
  JWT_AUDIENCE: autolytiq-dev
  SENDGRID_API_KEY: dev-sendgrid-key
  SENDGRID_FROM: notifications@example.com
  TWILIO_ACCOUNT_SID: ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  TWILIO_AUTH_TOKEN: your-dev-twilio-token
  TWILIO_MESSAGING_SERVICE_SID: MGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  TWILIO_CALLER_ID: "+15555550123"
