# syntax=docker/dockerfile:1.7
FROM node:20-alpine AS base
WORKDIR /app
ENV DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres?schema=public
ENV DIRECT_URL=${DATABASE_URL}
COPY package*.json tsconfig*.json tsup.config.ts vitest.config.ts ./
COPY prisma ./prisma
RUN npm ci
RUN npm run prisma:generate

FROM base AS build
COPY . .
RUN npm run build

FROM node:20-alpine AS runtime
ENV NODE_ENV=production
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules/.prisma ./node_modules/.prisma
COPY prisma ./prisma
EXPOSE 5000
CMD ["node", "dist/index.js"]
