apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEV3TWpneQpNakV4TURsYUZ3MDBOVEV3TWpneU1qRXhNRGxhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMUY2V1F3dS9vMCtlZEdpNVFKLzRNcktZSWpXNGtTK1ZNd0JXWDJFNUt6NHY3eXF0cwpjZUhtVGE5MEZZUWsxTThQTUNKV0EzMnlON1ovWDZ6V1B6OUR6ZjU5cTh6VUt6anlmeXRWc2Y3MjZrbzhpOTQ0Cmpha1grckdML3grcElpUGw0aFZJRUJUNWVvTjl3TnlxbE9rbE1lTzVscU55MnEraWk0VFJLa1AxK28rSjBFT0YKdVVwSVc4dWFNRkxSbGxQOTNjSmZYRHExQUxpbUhSY0ZiN25VR0pxOUxETU0rNlpqRDArMXAzYTZ0WVNURzVPagpVMnMzREhLa2J3LzlYRGRNV25GU3N6MlFjYzRCSDhNK1hmNXJvWjd6aEdlYmtvUkVkcmVTblVjUWxiMXpGRGtPClljenU1RmZRQUdIeS9CZk5ydnhQVEEzaVNZbXZWdzhzYWdJSkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFUSUhZbGhiV09kTTN1eVNaawpvK0ZlWThSVWNUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqaEdzSHc3UXp1d2VmVGlVbkhWendpeFp1My9JCkRXV0FJM0YycXVXMkc4Rmh1L1FPeWhCUVFMcU5wSXNSbkx1WHB6WlV3THhjWVBkalBTYWtpUE0wUXptR0E4ekYKTitRNnRUN0NicHE2TUM4NStTalgzNExWZ1p2V1pRQUtZN3djL2pvdWhzUjlKVTdzK2JLT25tUEozL2pUT0FLSAp1bVJnNDZOc1lZMXBobE01R2Z6OHpCYWlFYWszQVNvanJabUt2cHNxOFZ1eUtuN2R4UHN4VGkzRW44NGJFUXo0ClVvbHFjUFhHRVNxeWlKa3lxT2VKci9LZ1YvdlZoamJYZS8vRnNlNno0eGhyTldTVGxGUmZtMExXRDJBMmQwSC8KczZ2VC96UzRFMzZOVENMYUdxWkRmL1J5SS8yK1pjN3FTSFFXalpoK0VyMlFmcWNFZzJSQ3FjSWplUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://f06acfc6-37a7-4761-85f5-ba58283da756.k8s.ondigitalocean.com
  name: do-nyc3-autolytiq-cluster
contexts:
- context:
    cluster: do-nyc3-autolytiq-cluster
    user: do-nyc3-autolytiq-cluster-admin
  name: do-nyc3-autolytiq-cluster
current-context: do-nyc3-autolytiq-cluster
kind: Config
preferences: {}
users:
- name: do-nyc3-autolytiq-cluster-admin
  user:
    token: dop_v1_7215a24442ff397ee4707ed2f0a7d6f3c40317ea3a3715b31af1e0944bf1f5f4
