[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.6.1",
    "python-multipart>=0.0.20",
    "requests>=2.32.4",
    "scikit-learn>=1.7.0",
    "uvicorn>=0.35.0",
    "celery[redis]>=5.4.0",
    "redis>=5.2.1",
    "boto3>=1.35.63",
    "twilio>=9.2.3",
    "joblib>=1.4.2",
    "clickhouse-driver>=0.2.9",
    "psycopg2-binary>=2.9.10",
    "prometheus-client>=0.21.0",
]
