apiVersion: v1
kind: Secret
metadata:
  name: app-env
  namespace: autolytiq-prod
type: Opaque
data:
  # The value for all keys is "placeholder" (Base64 encoded)
  REDIS_URL: cGxhY2Vob2xkZXI=
  SENDGRID_API_KEY: cGxhY2Vob2xkZXI=
  SENDGRID_FROM_EMAIL: cGxhY2Vob2xkZXI=
  SENDGRID_WEBHOOK_SIGNING_KEY: cGxhY2Vob2xkZXI=
  TWILIO_ACCOUNT_SID: cGxhY2Vob2xkZXI=
  TWILIO_AUTH_TOKEN: cGxhY2Vob2xkZXI=
  TWILIO_MESSAGING_SERVICE_SID: cGxhY2Vob2xkZXI=
  PEXELS_API_KEY: cGxhY2Vob2xkZXI=
  AWS_ACCESS_KEY_ID: cGxhY2Vob2xkZXI=
  AWS_SECRET_ACCESS_KEY: cGxhY2Vob2xkZXI=
  S3_BUCKET: cGxhY2Vob2xkZXI=

