apiVersion: v1
kind: Secret
metadata:
  name: autolytiq-postgres
  namespace: autolytiq-dev
type: Opaque
stringData:
  POSTGRES_USER: autolytiq
  POSTGRES_PASSWORD: autolytiq
  POSTGRES_DB: autolytiq
