// Code generated by ent, DO NOT EDIT.

package tradein

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tradein type in the database.
	Label = "trade_in"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldDealID holds the string denoting the deal_id field in the database.
	FieldDealID = "deal_id"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldVin holds the string denoting the vin field in the database.
	FieldVin = "vin"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldMake holds the string denoting the make field in the database.
	FieldMake = "make"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldTrim holds the string denoting the trim field in the database.
	FieldTrim = "trim"
	// FieldMileage holds the string denoting the mileage field in the database.
	FieldMileage = "mileage"
	// FieldCondition holds the string denoting the condition field in the database.
	FieldCondition = "condition"
	// FieldEstimatedValue holds the string denoting the estimated_value field in the database.
	FieldEstimatedValue = "estimated_value"
	// FieldPayoffAmount holds the string denoting the payoff_amount field in the database.
	FieldPayoffAmount = "payoff_amount"
	// FieldActualCashValue holds the string denoting the actual_cash_value field in the database.
	FieldActualCashValue = "actual_cash_value"
	// FieldAllowance holds the string denoting the allowance field in the database.
	FieldAllowance = "allowance"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeDeal holds the string denoting the deal edge name in mutations.
	EdgeDeal = "deal"
	// EdgeCustomer holds the string denoting the customer edge name in mutations.
	EdgeCustomer = "customer"
	// Table holds the table name of the tradein in the database.
	Table = "trade_ins"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "trade_ins"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// DealTable is the table that holds the deal relation/edge.
	DealTable = "trade_ins"
	// DealInverseTable is the table name for the Deal entity.
	// It exists in this package in order to avoid circular dependency with the "deal" package.
	DealInverseTable = "deals"
	// DealColumn is the table column denoting the deal relation/edge.
	DealColumn = "deal_id"
	// CustomerTable is the table that holds the customer relation/edge.
	CustomerTable = "trade_ins"
	// CustomerInverseTable is the table name for the Customer entity.
	// It exists in this package in order to avoid circular dependency with the "customer" package.
	CustomerInverseTable = "customers"
	// CustomerColumn is the table column denoting the customer relation/edge.
	CustomerColumn = "customer_id"
)

// Columns holds all SQL columns for tradein fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldDealID,
	FieldCustomerID,
	FieldVin,
	FieldYear,
	FieldMake,
	FieldModel,
	FieldTrim,
	FieldMileage,
	FieldCondition,
	FieldEstimatedValue,
	FieldPayoffAmount,
	FieldActualCashValue,
	FieldAllowance,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// VinValidator is a validator for the "vin" field. It is called by the builders before save.
	VinValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the TradeIn queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByDealID orders the results by the deal_id field.
func ByDealID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDealID, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// ByVin orders the results by the vin field.
func ByVin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVin, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByMake orders the results by the make field.
func ByMake(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMake, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByTrim orders the results by the trim field.
func ByTrim(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrim, opts...).ToFunc()
}

// ByMileage orders the results by the mileage field.
func ByMileage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMileage, opts...).ToFunc()
}

// ByCondition orders the results by the condition field.
func ByCondition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCondition, opts...).ToFunc()
}

// ByEstimatedValue orders the results by the estimated_value field.
func ByEstimatedValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedValue, opts...).ToFunc()
}

// ByPayoffAmount orders the results by the payoff_amount field.
func ByPayoffAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayoffAmount, opts...).ToFunc()
}

// ByActualCashValue orders the results by the actual_cash_value field.
func ByActualCashValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCashValue, opts...).ToFunc()
}

// ByAllowance orders the results by the allowance field.
func ByAllowance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowance, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByDealField orders the results by deal field.
func ByDealField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDealStep(), sql.OrderByField(field, opts...))
	}
}

// ByCustomerField orders the results by customer field.
func ByCustomerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomerStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newDealStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DealInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DealTable, DealColumn),
	)
}
func newCustomerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CustomerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
	)
}
