apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autolytiq-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  tls:
    - hosts:
        - app.autolytiq.com
        - api.autolytiq.com
        - ml.autolytiq.com
        - dms.autolytiq.com
      secretName: autolytiq-tls
  rules:
    - host: app.autolytiq.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http
    - host: api.autolytiq.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  name: http
    - host: ml.autolytiq.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-service
                port:
                  name: http
    - host: dms.autolytiq.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http
