import { MemStorage } from './storage';

export function initializeComprehensiveSampleData(storage: MemStorage): void {
  // Add more comprehensive customers
  const additionalCustomers = [
    {
      firstName: "Jennifer",
      lastName: "Wilson",
      name: "Jennifer Wilson",
      email: "jennifer.wilson@email.com",
      phone: "(555) 567-8901",
      cellPhone: "(555) 567-8902",
      address: "456 Oak Avenue",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
      creditScore: 780,
      income: 95000,
      status: "hot",
      salesConsultant: "Sarah Jones",
      leadSource: "website",
      notes: "Interested in luxury vehicles, pre-approved financing",
      isActive: true
    },
    {
      firstName: "David",
      lastName: "Martinez",
      name: "David Martinez",
      email: "david.martinez@email.com",
      phone: "(555) 678-9012",
      cellPhone: "(555) 678-9013",
      address: "789 Elm Street",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      creditScore: 650,
      income: 65000,
      status: "warm",
      salesConsultant: "Mike Wilson",
      leadSource: "referral",
      notes: "Looking for fuel-efficient vehicle, needs financing options",
      isActive: true
    },
    {
      firstName: "Lisa",
      lastName: "Anderson",
      name: "Lisa Anderson",
      email: "lisa.anderson@email.com",
      phone: "(555) 789-0123",
      cellPhone: "(555) 789-0124",
      address: "321 Pine Road",
      city: "Houston",
      state: "TX",
      zipCode: "77002",
      creditScore: 720,
      income: 75000,
      status: "prospect",
      salesConsultant: "John Smith",
      leadSource: "walk-in",
      notes: "First-time buyer, needs guidance on vehicle selection",
      isActive: true
    },
    {
      firstName: "Kevin",
      lastName: "Thompson",
      name: "Kevin Thompson",
      email: "kevin.thompson@email.com",
      phone: "(555) 890-1234",
      cellPhone: "(555) 890-1235",
      address: "654 Cedar Lane",
      city: "San Antonio",
      state: "TX",
      zipCode: "78201",
      creditScore: 680,
      income: 55000,
      status: "cold",
      salesConsultant: "Sarah Jones",
      leadSource: "advertising",
      notes: "Budget-conscious buyer, looking for used vehicles",
      isActive: true
    },
    {
      firstName: "Amanda",
      lastName: "Clark",
      name: "Amanda Clark",
      email: "amanda.clark@email.com",
      phone: "(555) 901-2345",
      cellPhone: "(555) 901-2346",
      address: "987 Birch Street",
      city: "Fort Worth",
      state: "TX",
      zipCode: "76101",
      creditScore: 750,
      income: 85000,
      status: "customer",
      salesConsultant: "Mike Wilson",
      leadSource: "social-media",
      notes: "Repeat customer, interested in upgrading current vehicle",
      isActive: true
    },
    {
      firstName: "Brian",
      lastName: "Rodriguez",
      name: "Brian Rodriguez",
      email: "brian.rodriguez@email.com",
      phone: "(555) 012-3456",
      cellPhone: "(555) 012-3457",
      address: "123 Maple Drive",
      city: "Plano",
      state: "TX",
      zipCode: "75023",
      creditScore: 700,
      income: 80000,
      status: "hot",
      salesConsultant: "John Smith",
      leadSource: "website",
      notes: "Looking for family SUV, trade-in available",
      isActive: true
    },
    {
      firstName: "Michelle",
      lastName: "Lewis",
      name: "Michelle Lewis",
      email: "michelle.lewis@email.com",
      phone: "(555) 123-4567",
      cellPhone: "(555) 123-4568",
      address: "456 Willow Avenue",
      city: "Arlington",
      state: "TX",
      zipCode: "76001",
      creditScore: 690,
      income: 70000,
      status: "warm",
      salesConsultant: "Sarah Jones",
      leadSource: "referral",
      notes: "Interested in electric vehicles, environmentally conscious",
      isActive: true
    },
    {
      firstName: "Christopher",
      lastName: "Walker",
      name: "Christopher Walker",
      email: "chris.walker@email.com",
      phone: "(555) 234-5678",
      cellPhone: "(555) 234-5679",
      address: "789 Spruce Street",
      city: "Irving",
      state: "TX",
      zipCode: "75001",
      creditScore: 740,
      income: 90000,
      status: "prospect",
      salesConsultant: "Mike Wilson",
      leadSource: "phone",
      notes: "Business owner, needs commercial vehicle financing",
      isActive: true
    },
    {
      firstName: "Stephanie",
      lastName: "Hall",
      name: "Stephanie Hall",
      email: "stephanie.hall@email.com",
      phone: "(555) 345-6789",
      cellPhone: "(555) 345-6790",
      address: "321 Poplar Road",
      city: "Garland",
      state: "TX",
      zipCode: "75040",
      creditScore: 710,
      income: 60000,
      status: "customer",
      salesConsultant: "John Smith",
      leadSource: "walk-in",
      notes: "Recently purchased, satisfied with service",
      isActive: true
    },
    {
      firstName: "Mark",
      lastName: "Young",
      name: "Mark Young",
      email: "mark.young@email.com",
      phone: "(555) 456-7890",
      cellPhone: "(555) 456-7891",
      address: "654 Hickory Lane",
      city: "Mesquite",
      state: "TX",
      zipCode: "75149",
      creditScore: 660,
      income: 50000,
      status: "cold",
      salesConsultant: "Sarah Jones",
      leadSource: "advertising",
      notes: "Price-sensitive buyer, needs special financing",
      isActive: true
    }
  ];

  // Add more vehicles
  const additionalVehicles = [
    {
      make: "Honda",
      model: "Civic",
      year: 2023,
      vin: "1HGBH41JXMN109186",
      stockNumber: "H23001",
      color: "Silver",
      mileage: 25000,
      price: 24900,
      costPrice: 22000,
      msrp: 26500,
      status: "available",
      location: "Lot A",
      condition: "used",
      transmission: "Manual",
      engine: "1.5L 4-Cylinder",
      fuelType: "Gasoline",
      drivetrain: "FWD",
      bodyStyle: "Sedan",
      doors: 4,
      seats: 5,
      exteriorColor: "Silver",
      interiorColor: "Black",
      features: ["Bluetooth", "Backup Camera", "Apple CarPlay"],
      notes: "Low mileage, single owner"
    },
    {
      make: "Ford",
      model: "F-150",
      year: 2022,
      vin: "1FTFW1ET5DFC10312",
      stockNumber: "F22001",
      color: "Red",
      mileage: 35000,
      price: 42500,
      costPrice: 38000,
      msrp: 45000,
      status: "available",
      location: "Lot B",
      condition: "used",
      transmission: "Automatic",
      engine: "5.0L V8",
      fuelType: "Gasoline",
      drivetrain: "4WD",
      bodyStyle: "Pickup",
      doors: 4,
      seats: 5,
      exteriorColor: "Red",
      interiorColor: "Gray",
      features: ["4WD", "Towing Package", "Bed Liner"],
      notes: "Popular truck model, high demand"
    },
    {
      make: "Chevrolet",
      model: "Equinox",
      year: 2023,
      vin: "2GNAXKEV5L6157804",
      stockNumber: "C23001",
      color: "White",
      mileage: 15000,
      price: 32000,
      costPrice: 28500,
      msrp: 34500,
      status: "available",
      location: "Showroom",
      condition: "certified",
      transmission: "Automatic",
      engine: "1.5L Turbo",
      fuelType: "Gasoline",
      drivetrain: "AWD",
      bodyStyle: "SUV",
      doors: 4,
      seats: 5,
      exteriorColor: "White",
      interiorColor: "Black",
      features: ["AWD", "Heated Seats", "Remote Start"],
      notes: "Certified pre-owned with warranty"
    },
    {
      make: "Nissan",
      model: "Altima",
      year: 2022,
      vin: "1N4BL4BV8NC123456",
      stockNumber: "N22001",
      color: "Blue",
      mileage: 28000,
      price: 26500,
      costPrice: 23000,
      msrp: 28000,
      status: "available",
      location: "Lot A",
      condition: "used",
      transmission: "CVT",
      engine: "2.5L 4-Cylinder",
      fuelType: "Gasoline",
      drivetrain: "FWD",
      bodyStyle: "Sedan",
      doors: 4,
      seats: 5,
      exteriorColor: "Blue",
      interiorColor: "Beige",
      features: ["CVT Transmission", "Blind Spot Monitor", "Lane Assist"],
      notes: "Reliable family sedan"
    },
    {
      make: "BMW",
      model: "X3",
      year: 2023,
      vin: "5UX43DP05P9A12345",
      stockNumber: "B23001",
      color: "Black",
      mileage: 12000,
      price: 52000,
      costPrice: 47000,
      msrp: 55000,
      status: "available",
      location: "Showroom",
      condition: "certified",
      transmission: "Automatic",
      engine: "2.0L Turbo",
      fuelType: "Gasoline",
      drivetrain: "AWD",
      bodyStyle: "SUV",
      doors: 4,
      seats: 5,
      exteriorColor: "Black",
      interiorColor: "Tan",
      features: ["Premium Package", "Navigation", "Sunroof"],
      notes: "Luxury SUV with premium features"
    },
    {
      make: "Hyundai",
      model: "Elantra",
      year: 2023,
      vin: "KMHL14JA5PA123456",
      stockNumber: "H23002",
      color: "Gray",
      mileage: 18000,
      price: 22500,
      costPrice: 20000,
      msrp: 24000,
      status: "available",
      location: "Lot A",
      condition: "used",
      transmission: "Automatic",
      engine: "2.0L 4-Cylinder",
      fuelType: "Gasoline",
      drivetrain: "FWD",
      bodyStyle: "Sedan",
      doors: 4,
      seats: 5,
      exteriorColor: "Gray",
      interiorColor: "Black",
      features: ["Wireless Charging", "Android Auto", "Safety Suite"],
      notes: "Modern compact sedan with tech features"
    },
    {
      make: "Mazda",
      model: "CX-5",
      year: 2022,
      vin: "JM3KFBCM5N0123456",
      stockNumber: "M22001",
      color: "Red",
      mileage: 32000,
      price: 29500,
      costPrice: 26000,
      msrp: 31500,
      status: "available",
      location: "Lot B",
      condition: "used",
      transmission: "Automatic",
      engine: "2.5L 4-Cylinder",
      fuelType: "Gasoline",
      drivetrain: "AWD",
      bodyStyle: "SUV",
      doors: 4,
      seats: 5,
      exteriorColor: "Red",
      interiorColor: "Black",
      features: ["AWD", "Bose Audio", "Leather Seats"],
      notes: "Popular crossover SUV"
    },
    {
      make: "Volkswagen",
      model: "Jetta",
      year: 2023,
      vin: "3VW2B7AJ5PM123456",
      stockNumber: "V23001",
      color: "White",
      mileage: 8000,
      price: 25500,
      costPrice: 22500,
      msrp: 27000,
      status: "available",
      location: "Showroom",
      condition: "certified",
      transmission: "Automatic",
      engine: "1.4L Turbo",
      fuelType: "Gasoline",
      drivetrain: "FWD",
      bodyStyle: "Sedan",
      doors: 4,
      seats: 5,
      exteriorColor: "White",
      interiorColor: "Gray",
      features: ["Turbo Engine", "Digital Cockpit", "App Connect"],
      notes: "European engineering with modern features"
    }
  ];

  // Add customers to storage
  additionalCustomers.forEach(async (customerData) => {
    try {
      await storage.createCustomer(customerData);
    } catch (error) {
      console.error('Error creating customer:', error);
    }
  });

  // Add vehicles to storage  
  additionalVehicles.forEach(async (vehicleData) => {
    try {
      await storage.createVehicle(vehicleData);
    } catch (error) {
      console.error('Error creating vehicle:', error);
    }
  });

  console.log('✅ Comprehensive sample data initialized successfully');
}