// Code generated by ent, DO NOT EDIT.

package lead

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/autolytiq/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Lead {
	return predicate.Lead(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Lead {
	return predicate.Lead(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldTenantID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldCustomerID, v))
}

// AssignedToID applies equality check predicate on the "assigned_to_id" field. It's identical to AssignedToIDEQ.
func AssignedToID(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldAssignedToID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldSource, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldStatus, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldScore, v))
}

// VehicleInterest applies equality check predicate on the "vehicle_interest" field. It's identical to VehicleInterestEQ.
func VehicleInterest(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldVehicleInterest, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContainsFold(FieldTenantID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDIsNil applies the IsNil predicate on the "customer_id" field.
func CustomerIDIsNil() predicate.Lead {
	return predicate.Lead(sql.FieldIsNull(FieldCustomerID))
}

// CustomerIDNotNil applies the NotNil predicate on the "customer_id" field.
func CustomerIDNotNil() predicate.Lead {
	return predicate.Lead(sql.FieldNotNull(FieldCustomerID))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContainsFold(FieldCustomerID, v))
}

// AssignedToIDEQ applies the EQ predicate on the "assigned_to_id" field.
func AssignedToIDEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldAssignedToID, v))
}

// AssignedToIDNEQ applies the NEQ predicate on the "assigned_to_id" field.
func AssignedToIDNEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldAssignedToID, v))
}

// AssignedToIDIn applies the In predicate on the "assigned_to_id" field.
func AssignedToIDIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldAssignedToID, vs...))
}

// AssignedToIDNotIn applies the NotIn predicate on the "assigned_to_id" field.
func AssignedToIDNotIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldAssignedToID, vs...))
}

// AssignedToIDGT applies the GT predicate on the "assigned_to_id" field.
func AssignedToIDGT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldAssignedToID, v))
}

// AssignedToIDGTE applies the GTE predicate on the "assigned_to_id" field.
func AssignedToIDGTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldAssignedToID, v))
}

// AssignedToIDLT applies the LT predicate on the "assigned_to_id" field.
func AssignedToIDLT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldAssignedToID, v))
}

// AssignedToIDLTE applies the LTE predicate on the "assigned_to_id" field.
func AssignedToIDLTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldAssignedToID, v))
}

// AssignedToIDContains applies the Contains predicate on the "assigned_to_id" field.
func AssignedToIDContains(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContains(FieldAssignedToID, v))
}

// AssignedToIDHasPrefix applies the HasPrefix predicate on the "assigned_to_id" field.
func AssignedToIDHasPrefix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasPrefix(FieldAssignedToID, v))
}

// AssignedToIDHasSuffix applies the HasSuffix predicate on the "assigned_to_id" field.
func AssignedToIDHasSuffix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasSuffix(FieldAssignedToID, v))
}

// AssignedToIDIsNil applies the IsNil predicate on the "assigned_to_id" field.
func AssignedToIDIsNil() predicate.Lead {
	return predicate.Lead(sql.FieldIsNull(FieldAssignedToID))
}

// AssignedToIDNotNil applies the NotNil predicate on the "assigned_to_id" field.
func AssignedToIDNotNil() predicate.Lead {
	return predicate.Lead(sql.FieldNotNull(FieldAssignedToID))
}

// AssignedToIDEqualFold applies the EqualFold predicate on the "assigned_to_id" field.
func AssignedToIDEqualFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEqualFold(FieldAssignedToID, v))
}

// AssignedToIDContainsFold applies the ContainsFold predicate on the "assigned_to_id" field.
func AssignedToIDContainsFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContainsFold(FieldAssignedToID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContainsFold(FieldSource, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContainsFold(FieldStatus, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldScore, v))
}

// VehicleInterestEQ applies the EQ predicate on the "vehicle_interest" field.
func VehicleInterestEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldVehicleInterest, v))
}

// VehicleInterestNEQ applies the NEQ predicate on the "vehicle_interest" field.
func VehicleInterestNEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldVehicleInterest, v))
}

// VehicleInterestIn applies the In predicate on the "vehicle_interest" field.
func VehicleInterestIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldVehicleInterest, vs...))
}

// VehicleInterestNotIn applies the NotIn predicate on the "vehicle_interest" field.
func VehicleInterestNotIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldVehicleInterest, vs...))
}

// VehicleInterestGT applies the GT predicate on the "vehicle_interest" field.
func VehicleInterestGT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldVehicleInterest, v))
}

// VehicleInterestGTE applies the GTE predicate on the "vehicle_interest" field.
func VehicleInterestGTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldVehicleInterest, v))
}

// VehicleInterestLT applies the LT predicate on the "vehicle_interest" field.
func VehicleInterestLT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldVehicleInterest, v))
}

// VehicleInterestLTE applies the LTE predicate on the "vehicle_interest" field.
func VehicleInterestLTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldVehicleInterest, v))
}

// VehicleInterestContains applies the Contains predicate on the "vehicle_interest" field.
func VehicleInterestContains(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContains(FieldVehicleInterest, v))
}

// VehicleInterestHasPrefix applies the HasPrefix predicate on the "vehicle_interest" field.
func VehicleInterestHasPrefix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasPrefix(FieldVehicleInterest, v))
}

// VehicleInterestHasSuffix applies the HasSuffix predicate on the "vehicle_interest" field.
func VehicleInterestHasSuffix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasSuffix(FieldVehicleInterest, v))
}

// VehicleInterestIsNil applies the IsNil predicate on the "vehicle_interest" field.
func VehicleInterestIsNil() predicate.Lead {
	return predicate.Lead(sql.FieldIsNull(FieldVehicleInterest))
}

// VehicleInterestNotNil applies the NotNil predicate on the "vehicle_interest" field.
func VehicleInterestNotNil() predicate.Lead {
	return predicate.Lead(sql.FieldNotNull(FieldVehicleInterest))
}

// VehicleInterestEqualFold applies the EqualFold predicate on the "vehicle_interest" field.
func VehicleInterestEqualFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEqualFold(FieldVehicleInterest, v))
}

// VehicleInterestContainsFold applies the ContainsFold predicate on the "vehicle_interest" field.
func VehicleInterestContainsFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContainsFold(FieldVehicleInterest, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Lead {
	return predicate.Lead(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Lead {
	return predicate.Lead(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Lead {
	return predicate.Lead(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Lead {
	return predicate.Lead(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Lead {
	return predicate.Lead(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Lead {
	return predicate.Lead(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Lead {
	return predicate.Lead(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.Lead {
	return predicate.Lead(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.Lead {
	return predicate.Lead(func(s *sql.Selector) {
		step := newCustomerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedTo applies the HasEdge predicate on the "assigned_to" edge.
func HasAssignedTo() predicate.Lead {
	return predicate.Lead(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssignedToTable, AssignedToColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedToWith applies the HasEdge predicate on the "assigned_to" edge with a given conditions (other predicates).
func HasAssignedToWith(preds ...predicate.User) predicate.Lead {
	return predicate.Lead(func(s *sql.Selector) {
		step := newAssignedToStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Lead) predicate.Lead {
	return predicate.Lead(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Lead) predicate.Lead {
	return predicate.Lead(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Lead) predicate.Lead {
	return predicate.Lead(sql.NotPredicates(p))
}
