/**
 * Audit Service
 * 
 * Comprehensive audit trail for all entity changes.
 * Tracks who, what, when, and how for compliance and debugging.
 */

import type { NeonHttpDatabase } from 'drizzle-orm/neon-http';
import { desc, eq, and } from 'drizzle-orm';
import {
  auditLogs,
  type AuditLog,
  type InsertAuditLog,
} from '@shared/schema';

export interface AuditLogParams {
  actorId?: string;
  actorName?: string;
  entityType: string;
  entityId: string;
  action: string;
  before?: any;
  after?: any;
  changes?: Record<string, { from: any; to: any }>;
  metadata?: Record<string, any>;
  ipAddress?: string;
  userAgent?: string;
}

export class AuditService {
  /**
   * Log an entity change
   */
  static async log(
    params: AuditLogParams,
    db: NeonHttpDatabase
  ): Promise<AuditLog> {
    const auditEntry: InsertAuditLog = {
      actorId: params.actorId,
      actorName: params.actorName,
      entityType: params.entityType,
      entityId: params.entityId,
      action: params.action,
      before: params.before ? JSON.parse(JSON.stringify(params.before)) : null,
      after: params.after ? JSON.parse(JSON.stringify(params.after)) : null,
      changes: params.changes ? JSON.parse(JSON.stringify(params.changes)) : null,
      metadata: params.metadata ? JSON.parse(JSON.stringify(params.metadata)) : null,
      ipAddress: params.ipAddress,
      userAgent: params.userAgent,
    };

    const result = await db
      .insert(auditLogs)
      .values(auditEntry)
      .returning();

    return result[0];
  }

  /**
   * Get audit trail for a specific entity
   */
  static async getAuditTrail(
    entityType: string,
    entityId: string,
    db: NeonHttpDatabase,
    limit: number = 100
  ): Promise<AuditLog[]> {
    const logs = await db
      .select()
      .from(auditLogs)
      .where(
        and(
          eq(auditLogs.entityType, entityType),
          eq(auditLogs.entityId, entityId)
        )
      )
      .orderBy(desc(auditLogs.createdAt))
      .limit(limit);

    return logs;
  }

  /**
   * Get recent activity by an actor
   */
  static async getActorActivity(
    actorId: string,
    db: NeonHttpDatabase,
    limit: number = 50
  ): Promise<AuditLog[]> {
    const logs = await db
      .select()
      .from(auditLogs)
      .where(eq(auditLogs.actorId, actorId))
      .orderBy(desc(auditLogs.createdAt))
      .limit(limit);

    return logs;
  }

  /**
   * Get all recent audit logs (for admin review)
   */
  static async getRecentLogs(
    db: NeonHttpDatabase,
    limit: number = 100
  ): Promise<AuditLog[]> {
    const logs = await db
      .select()
      .from(auditLogs)
      .orderBy(desc(auditLogs.createdAt))
      .limit(limit);

    return logs;
  }

  /**
   * Helper: Compute changes between before and after states
   */
  static computeChanges(
    before: Record<string, any>,
    after: Record<string, any>
  ): Record<string, { from: any; to: any }> {
    const changes: Record<string, { from: any; to: any }> = {};

    // Check all keys in 'after' state
    for (const key in after) {
      if (before[key] !== after[key]) {
        changes[key] = {
          from: before[key],
          to: after[key],
        };
      }
    }

    // Check for removed keys (in 'before' but not in 'after')
    for (const key in before) {
      if (!(key in after)) {
        changes[key] = {
          from: before[key],
          to: undefined,
        };
      }
    }

    return changes;
  }

  /**
   * Helper: Log vehicle creation
   */
  static async logVehicleCreate(
    vehicleId: string,
    vehicleData: any,
    actorId?: string,
    actorName?: string,
    db?: NeonHttpDatabase
  ): Promise<AuditLog | null> {
    if (!db) return null;

    return this.log(
      {
        actorId,
        actorName,
        entityType: 'vehicle',
        entityId: vehicleId,
        action: 'create',
        after: vehicleData,
        metadata: {
          source: 'inventory_management',
        },
      },
      db
    );
  }

  /**
   * Helper: Log vehicle update
   */
  static async logVehicleUpdate(
    vehicleId: string,
    before: any,
    after: any,
    actorId?: string,
    actorName?: string,
    db?: NeonHttpDatabase
  ): Promise<AuditLog | null> {
    if (!db) return null;

    const changes = this.computeChanges(before, after);

    return this.log(
      {
        actorId,
        actorName,
        entityType: 'vehicle',
        entityId: vehicleId,
        action: 'update',
        before,
        after,
        changes,
        metadata: {
          source: 'inventory_management',
          fieldsChanged: Object.keys(changes),
        },
      },
      db
    );
  }

  /**
   * Helper: Log stock number override
   */
  static async logStockOverride(
    vehicleId: string,
    vin: string,
    autoGeneratedStock: string,
    manualStock: string,
    actorId?: string,
    actorName?: string,
    db?: NeonHttpDatabase
  ): Promise<AuditLog | null> {
    if (!db) return null;

    return this.log(
      {
        actorId,
        actorName,
        entityType: 'vehicle',
        entityId: vehicleId,
        action: 'override_stock',
        before: { stockNo: autoGeneratedStock, stockIsOverride: false },
        after: { stockNo: manualStock, stockIsOverride: true },
        metadata: {
          vin,
          autoGenerated: autoGeneratedStock,
          manualOverride: manualStock,
          reason: 'Manual stock number override',
        },
      },
      db
    );
  }

  /**
   * Helper: Log deal creation
   */
  static async logDealCreate(
    dealId: string,
    dealData: any,
    actorId?: string,
    actorName?: string,
    db?: NeonHttpDatabase
  ): Promise<AuditLog | null> {
    if (!db) return null;

    return this.log(
      {
        actorId,
        actorName,
        entityType: 'deal',
        entityId: dealId,
        action: 'create',
        after: dealData,
        metadata: {
          source: 'deal_desk',
        },
      },
      db
    );
  }

  /**
   * Helper: Log deal update
   */
  static async logDealUpdate(
    dealId: string,
    before: any,
    after: any,
    actorId?: string,
    actorName?: string,
    db?: NeonHttpDatabase
  ): Promise<AuditLog | null> {
    if (!db) return null;

    const changes = this.computeChanges(before, after);

    return this.log(
      {
        actorId,
        actorName,
        entityType: 'deal',
        entityId: dealId,
        action: 'update',
        before,
        after,
        changes,
        metadata: {
          source: 'deal_desk',
          fieldsChanged: Object.keys(changes),
        },
      },
      db
    );
  }

  /**
   * Helper: Format audit log for display
   */
  static formatAuditLog(log: AuditLog): string {
    const timestamp = new Date(log.createdAt).toLocaleString();
    const actor = log.actorName || log.actorId || 'System';
    const action = log.action.replace(/_/g, ' ').toUpperCase();
    
    return `[${timestamp}] ${actor} - ${action} ${log.entityType} #${log.entityId}`;
  }

  /**
   * Helper: Get summary of changes from audit log
   */
  static getChangesSummary(log: AuditLog): string[] {
    if (!log.changes) return [];

    const changes = log.changes as Record<string, { from: any; to: any }>;
    const summary: string[] = [];

    for (const [field, change] of Object.entries(changes)) {
      summary.push(`${field}: ${change.from} → ${change.to}`);
    }

    return summary;
  }
}
