apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: autolytiq-dev
  labels:
    app.kubernetes.io/name: autolytiq-backend
    app.kubernetes.io/part-of: autolytiq
spec:
  selector:
    app.kubernetes.io/name: autolytiq-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
