import { useCallback, useMemo, useState } from 'react';
import { useLocation, useSearch } from 'wouter';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { useToast } from '@/hooks/use-toast';
import {
  ComplianceChecklistDto,
  ComplianceGroup,
  ComplianceItemDto,
  ComplianceUpdateInput,
  fetchComplianceChecklist,
  fetchStateComplianceRequirements,
  generateComplianceDocument,
  StateComplianceRequirementDto,
  updateComplianceChecklistItems,
} from '../api';
import { Loader2, FileText, RefreshCcw, CheckCircle } from 'lucide-react';

function formatDate(value?: string | null) {
  if (!value) return null;
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return null;
  return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(parsed);
}

function groupTitle(group: ComplianceGroup) {
  switch (group) {
    case 'federal':
      return 'Federal Requirements';
    case 'state':
      return 'State Requirements';
    case 'lender':
      return 'Lender Stipulations';
    case 'internal':
      return 'Internal Workflow';
    default:
      return group;
  }
}

function ComplianceGroupCard({
  group,
  items,
  onToggle,
  disabled,
}: {
  group: ComplianceGroup;
  items: ComplianceItemDto[];
  onToggle: (group: ComplianceGroup, item: ComplianceItemDto) => void;
  disabled?: boolean;
}) {
  return (
    <Card className="h-full">
      <CardHeader className="flex flex-row items-center justify-between gap-2">
        <div>
          <CardTitle className="text-lg font-semibold">{groupTitle(group)}</CardTitle>
          <p className="text-sm text-muted-foreground">
            {items.filter((item) => item.required !== false).length} required • {items.length} total
          </p>
        </div>
      </CardHeader>
      <CardContent className="p-0">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[48px]" />
              <TableHead>Requirement</TableHead>
              <TableHead className="hidden md:table-cell">Details</TableHead>
              <TableHead className="w-[140px] text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {items.length === 0 ? (
              <TableRow>
                <TableCell colSpan={4} className="py-10 text-center text-sm text-muted-foreground">
                  No requirements configured.
                </TableCell>
              </TableRow>
            ) : (
              items.map((item) => {
                const dueDate = formatDate(item.dueDate);
                return (
                  <TableRow key={item.id} className={item.completed ? 'bg-muted/40' : undefined}>
                    <TableCell>
                      <Checkbox
                        checked={item.completed}
                        disabled={disabled}
                        onCheckedChange={() => onToggle(group, item)}
                        aria-label={`Toggle ${item.title}`}
                      />
                    </TableCell>
                    <TableCell className="align-top">
                      <div className="flex flex-col gap-1">
                        <span className="font-medium leading-snug text-foreground">{item.title}</span>
                        <div className="flex flex-wrap items-center gap-2">
                          {item.required === false && <Badge variant="outline">Optional</Badge>}
                          {item.autoGenerated && <Badge variant="secondary">Auto-generated</Badge>}
                          {dueDate && <Badge variant="outline">Due {dueDate}</Badge>}
                          {item.statute && <Badge variant="outline">{item.statute}</Badge>}
                        </div>
                      </div>
                    </TableCell>
                    <TableCell className="hidden align-top text-sm text-muted-foreground md:table-cell">
                      <p>{item.description}</p>
                      {item.notes && <p className="mt-2 text-xs text-muted-foreground">Notes: {item.notes}</p>}
                      {item.documentUrl && (
                        <p className="mt-2 text-xs text-muted-foreground">
                          Document uploaded {formatDate(item.completedAt) ?? ''}
                        </p>
                      )}
                    </TableCell>
                    <TableCell className="align-top text-right">
                      <div className="flex flex-col items-end gap-2">
                        {item.documentUrl ? (
                          <Button variant="ghost" size="sm" asChild>
                            <a href={item.documentUrl} target="_blank" rel="noopener noreferrer">
                              <FileText className="mr-2 h-4 w-4" /> View
                            </a>
                          </Button>
                        ) : item.autoGenerateType ? (
                          <Badge variant="outline">Needs document</Badge>
                        ) : null}
                        {item.completed && (
                          <div className="flex items-center gap-1 text-xs text-emerald-600">
                            <CheckCircle className="h-3.5 w-3.5" />
                            <span>{formatDate(item.completedAt) ?? 'Completed'}</span>
                          </div>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                );
              })
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}

export default function ComplianceEngine() {
  const search = useSearch();
  const initialSearch = search ? new URLSearchParams(search) : null;
  const initialDealId = initialSearch?.get('dealId') ?? '';
  const [dealIdInput, setDealIdInput] = useState(initialDealId);
  const [activeDealId, setActiveDealId] = useState(initialDealId);
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const {
    data: checklist,
    isLoading,
    isFetching,
    error,
  } = useQuery<ComplianceChecklistDto>({
    queryKey: ['fi', 'compliance', activeDealId],
    queryFn: () => fetchComplianceChecklist(activeDealId),
    enabled: Boolean(activeDealId),
    refetchInterval: activeDealId ? 30000 : false,
  });

  const { data: stateRequirements } = useQuery<StateComplianceRequirementDto>({
    queryKey: ['fi', 'compliance', 'state', checklist?.state],
    queryFn: () => fetchStateComplianceRequirements(checklist!.state),
    enabled: Boolean(checklist?.state),
  });

  const updateMutation = useMutation({
    mutationFn: updateComplianceChecklistItems,
    onSuccess: (updated) => {
      queryClient.setQueryData(['fi', 'compliance', updated.dealId], updated);
      toast({ title: 'Compliance checklist updated' });
    },
    onError: (mutationError: any) => {
      toast({
        title: 'Unable to update compliance checklist',
        description: mutationError?.message ?? 'An unexpected error occurred.',
        variant: 'destructive',
      });
    },
  });

  const generateMutation = useMutation({
    mutationFn: ({ dealId, type }: { dealId: string; type: 'buyers-guide' | 'tila' }) =>
      generateComplianceDocument(dealId, type),
    onSuccess: (result) => {
      queryClient.setQueryData(['fi', 'compliance', result.checklist.dealId], result.checklist);
    },
    onError: (mutationError: any) => {
      toast({
        title: 'Unable to generate document',
        description: mutationError?.message ?? 'An unexpected error occurred while generating the document.',
        variant: 'destructive',
      });
    },
  });

  const allItems = useMemo(() => {
    if (!checklist) return [] as Array<{ group: ComplianceGroup; item: ComplianceItemDto }>;
    return (Object.keys(checklist.groups) as ComplianceGroup[]).flatMap((group) =>
      checklist.groups[group].map((item) => ({ group, item })),
    );
  }, [checklist]);

  const pendingAutoDocuments = useMemo(() => {
    const types = new Set<'buyers-guide' | 'tila'>();
    for (const entry of allItems) {
      if (entry.item.autoGenerateType && !entry.item.documentUrl) {
        types.add(entry.item.autoGenerateType);
      }
    }
    return Array.from(types);
  }, [allItems]);

  const handleToggleItem = useCallback(
    (group: ComplianceGroup, item: ComplianceItemDto) => {
      if (!activeDealId) return;
      const payload: ComplianceUpdateInput = {
        group,
        itemId: item.id,
        completed: !item.completed,
      };
      updateMutation.mutate({ dealId: activeDealId, updates: [payload] });
    },
    [activeDealId, updateMutation],
  );

  const handleLoadChecklist = useCallback(() => {
    if (!dealIdInput.trim()) {
      toast({
        title: 'Deal ID required',
        description: 'Enter a deal jacket ID to load compliance requirements.',
        variant: 'destructive',
      });
      return;
    }
    const nextDealId = dealIdInput.trim();
    setActiveDealId(nextDealId);
    setLocation(`/finance/compliance?dealId=${encodeURIComponent(nextDealId)}`);
  }, [dealIdInput, setLocation, toast]);

  const handleGenerateMissing = useCallback(async () => {
    if (!activeDealId) {
      toast({
        title: 'Select a deal first',
        description: 'Load a deal to generate compliance documents.',
        variant: 'destructive',
      });
      return;
    }
    if (pendingAutoDocuments.length === 0) {
      toast({ title: 'No documents to generate', description: 'All auto-generated documents are already present.' });
      return;
    }

    for (const type of pendingAutoDocuments) {
      const result = await generateMutation.mutateAsync({ dealId: activeDealId, type });
      toast({ title: `${result.document.fileName} generated`, description: 'Document uploaded to deal jacket.' });
    }
  }, [activeDealId, generateMutation, pendingAutoDocuments, toast]);

  const handleCompleteAll = useCallback(() => {
    if (!activeDealId) return;
    updateMutation.mutate({ dealId: activeDealId, completeAll: true });
  }, [activeDealId, updateMutation]);

  const fundingReady = checklist?.progress.isComplete ?? false;
  const disableActions = updateMutation.isPending || generateMutation.isPending;

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Input
            placeholder="Enter Deal Jacket ID"
            value={dealIdInput}
            onChange={(event) => setDealIdInput(event.target.value)}
            className="w-64"
          />
          <Button onClick={handleLoadChecklist} disabled={!dealIdInput.trim()}>
            Load Checklist
          </Button>
        </div>
        <div className="flex items-center gap-3">
          <Badge variant={fundingReady ? 'default' : 'outline'} className="text-sm">
            {fundingReady ? 'Funding Ready' : 'Funding Locked'}
          </Badge>
          {activeDealId && (
            <Button
              variant="outline"
              onClick={() => queryClient.invalidateQueries({ queryKey: ['fi', 'compliance', activeDealId] })}
              disabled={isFetching}
            >
              {isFetching ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <RefreshCcw className="mr-2 h-4 w-4" />}
              Refresh
            </Button>
          )}
        </div>
      </div>

      {error && (
        <Card className="border-destructive bg-destructive/10">
          <CardContent className="py-6">
            <p className="text-sm text-destructive-foreground">
              Unable to load compliance checklist. {error instanceof Error ? error.message : String(error)}
            </p>
          </CardContent>
        </Card>
      )}

      {isLoading && activeDealId ? (
        <div className="flex h-64 items-center justify-center rounded-lg border">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </div>
      ) : checklist ? (
        <>
          <div className="grid gap-4 lg:grid-cols-3">
            <Card className="lg:col-span-2">
              <CardHeader className="flex flex-row items-start justify-between gap-4">
                <div>
                  <CardTitle className="text-xl font-semibold">Compliance Progress</CardTitle>
                  <p className="text-sm text-muted-foreground">
                    {checklist.progress.completedItems} of {checklist.progress.totalItems} required items complete
                  </p>
                </div>
                <div className="text-right text-sm text-muted-foreground">
                  <p>{checklist.metadata.stateLabel}</p>
                  <p>Deal #{checklist.metadata.dealNumber}</p>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <div className="flex items-center justify-between text-sm font-medium">
                    <span>Overall Completion</span>
                    <span>{checklist.progress.percentComplete.toFixed(2)}%</span>
                  </div>
                  <Progress value={checklist.progress.percentComplete} />
                </div>
                <div className="grid gap-4 md:grid-cols-3">
                  <div>
                    <p className="text-xs text-muted-foreground">Customer</p>
                    <p className="text-sm font-medium text-foreground">{checklist.metadata.customerName}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Vehicle</p>
                    <p className="text-sm font-medium text-foreground">{checklist.metadata.vehicleDescription}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Lender</p>
                    <p className="text-sm font-medium text-foreground">
                      {checklist.metadata.lenderName ?? 'No lender selected'}
                    </p>
                  </div>
                </div>
                <div className="flex flex-wrap items-center gap-3">
                  <Button
                    variant="secondary"
                    onClick={handleGenerateMissing}
                    disabled={disableActions || pendingAutoDocuments.length === 0}
                  >
                    {generateMutation.isPending ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <RefreshCcw className="mr-2 h-4 w-4" />
                    )}
                    Generate Missing Documents
                  </Button>
                  <Button
                    onClick={handleCompleteAll}
                    disabled={disableActions || !activeDealId}
                    variant={fundingReady ? 'default' : 'outline'}
                  >
                    {updateMutation.isPending ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <CheckCircle className="mr-2 h-4 w-4" />
                    )}
                    Mark All Complete & Submit for Funding
                  </Button>
                  <span className="text-xs text-muted-foreground">
                    Funding submission unlocks automatically once all required items are complete.
                  </span>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="text-base font-semibold">State Compliance Notes</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3 text-sm text-muted-foreground">
                {stateRequirements ? (
                  <>
                    <p>
                      {stateRequirements.label} requires {stateRequirements.requirements.length} compliance documents for this
                      deal.
                    </p>
                    <ul className="list-disc space-y-2 pl-4">
                      {stateRequirements.requirements.map((requirement) => (
                        <li key={requirement.id}>
                          <span className="font-medium text-foreground">{requirement.title}</span>
                          <br />
                          <span>{requirement.description}</span>
                        </li>
                      ))}
                    </ul>
                  </>
                ) : (
                  <p>No state-specific requirements loaded.</p>
                )}
              </CardContent>
            </Card>
          </div>

          <div className="grid gap-4 xl:grid-cols-2">
            {(Object.keys(checklist.groups) as ComplianceGroup[]).map((group) => (
              <ComplianceGroupCard
                key={group}
                group={group}
                items={checklist.groups[group]}
                onToggle={handleToggleItem}
                disabled={disableActions || !activeDealId}
              />
            ))}
          </div>
        </>
      ) : (
        <Card>
          <CardContent className="py-12 text-center text-sm text-muted-foreground">
            Enter a deal jacket ID to load the compliance engine.
          </CardContent>
        </Card>
      )}
    </div>
  );
}
