// Code generated by ent, DO NOT EDIT.

package deal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/autolytiq/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Deal {
	return predicate.Deal(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Deal {
	return predicate.Deal(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldTenantID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldCustomerID, v))
}

// VehicleID applies equality check predicate on the "vehicle_id" field. It's identical to VehicleIDEQ.
func VehicleID(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldVehicleID, v))
}

// SalespersonID applies equality check predicate on the "salesperson_id" field. It's identical to SalespersonIDEQ.
func SalespersonID(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldSalespersonID, v))
}

// DealNumber applies equality check predicate on the "deal_number" field. It's identical to DealNumberEQ.
func DealNumber(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldDealNumber, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldStatus, v))
}

// Stage applies equality check predicate on the "stage" field. It's identical to StageEQ.
func Stage(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldStage, v))
}

// SalePrice applies equality check predicate on the "sale_price" field. It's identical to SalePriceEQ.
func SalePrice(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldSalePrice, v))
}

// DownPayment applies equality check predicate on the "down_payment" field. It's identical to DownPaymentEQ.
func DownPayment(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldDownPayment, v))
}

// AmountFinanced applies equality check predicate on the "amount_financed" field. It's identical to AmountFinancedEQ.
func AmountFinanced(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldAmountFinanced, v))
}

// MonthlyPayment applies equality check predicate on the "monthly_payment" field. It's identical to MonthlyPaymentEQ.
func MonthlyPayment(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldMonthlyPayment, v))
}

// TermMonths applies equality check predicate on the "term_months" field. It's identical to TermMonthsEQ.
func TermMonths(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldTermMonths, v))
}

// InterestRate applies equality check predicate on the "interest_rate" field. It's identical to InterestRateEQ.
func InterestRate(v float64) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldInterestRate, v))
}

// GrossProfit applies equality check predicate on the "gross_profit" field. It's identical to GrossProfitEQ.
func GrossProfit(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldGrossProfit, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContainsFold(FieldTenantID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDIsNil applies the IsNil predicate on the "customer_id" field.
func CustomerIDIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldCustomerID))
}

// CustomerIDNotNil applies the NotNil predicate on the "customer_id" field.
func CustomerIDNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldCustomerID))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContainsFold(FieldCustomerID, v))
}

// VehicleIDEQ applies the EQ predicate on the "vehicle_id" field.
func VehicleIDEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldVehicleID, v))
}

// VehicleIDNEQ applies the NEQ predicate on the "vehicle_id" field.
func VehicleIDNEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldVehicleID, v))
}

// VehicleIDIn applies the In predicate on the "vehicle_id" field.
func VehicleIDIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldVehicleID, vs...))
}

// VehicleIDNotIn applies the NotIn predicate on the "vehicle_id" field.
func VehicleIDNotIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldVehicleID, vs...))
}

// VehicleIDGT applies the GT predicate on the "vehicle_id" field.
func VehicleIDGT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldVehicleID, v))
}

// VehicleIDGTE applies the GTE predicate on the "vehicle_id" field.
func VehicleIDGTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldVehicleID, v))
}

// VehicleIDLT applies the LT predicate on the "vehicle_id" field.
func VehicleIDLT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldVehicleID, v))
}

// VehicleIDLTE applies the LTE predicate on the "vehicle_id" field.
func VehicleIDLTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldVehicleID, v))
}

// VehicleIDContains applies the Contains predicate on the "vehicle_id" field.
func VehicleIDContains(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContains(FieldVehicleID, v))
}

// VehicleIDHasPrefix applies the HasPrefix predicate on the "vehicle_id" field.
func VehicleIDHasPrefix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasPrefix(FieldVehicleID, v))
}

// VehicleIDHasSuffix applies the HasSuffix predicate on the "vehicle_id" field.
func VehicleIDHasSuffix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasSuffix(FieldVehicleID, v))
}

// VehicleIDIsNil applies the IsNil predicate on the "vehicle_id" field.
func VehicleIDIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldVehicleID))
}

// VehicleIDNotNil applies the NotNil predicate on the "vehicle_id" field.
func VehicleIDNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldVehicleID))
}

// VehicleIDEqualFold applies the EqualFold predicate on the "vehicle_id" field.
func VehicleIDEqualFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEqualFold(FieldVehicleID, v))
}

// VehicleIDContainsFold applies the ContainsFold predicate on the "vehicle_id" field.
func VehicleIDContainsFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContainsFold(FieldVehicleID, v))
}

// SalespersonIDEQ applies the EQ predicate on the "salesperson_id" field.
func SalespersonIDEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldSalespersonID, v))
}

// SalespersonIDNEQ applies the NEQ predicate on the "salesperson_id" field.
func SalespersonIDNEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldSalespersonID, v))
}

// SalespersonIDIn applies the In predicate on the "salesperson_id" field.
func SalespersonIDIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldSalespersonID, vs...))
}

// SalespersonIDNotIn applies the NotIn predicate on the "salesperson_id" field.
func SalespersonIDNotIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldSalespersonID, vs...))
}

// SalespersonIDGT applies the GT predicate on the "salesperson_id" field.
func SalespersonIDGT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldSalespersonID, v))
}

// SalespersonIDGTE applies the GTE predicate on the "salesperson_id" field.
func SalespersonIDGTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldSalespersonID, v))
}

// SalespersonIDLT applies the LT predicate on the "salesperson_id" field.
func SalespersonIDLT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldSalespersonID, v))
}

// SalespersonIDLTE applies the LTE predicate on the "salesperson_id" field.
func SalespersonIDLTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldSalespersonID, v))
}

// SalespersonIDContains applies the Contains predicate on the "salesperson_id" field.
func SalespersonIDContains(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContains(FieldSalespersonID, v))
}

// SalespersonIDHasPrefix applies the HasPrefix predicate on the "salesperson_id" field.
func SalespersonIDHasPrefix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasPrefix(FieldSalespersonID, v))
}

// SalespersonIDHasSuffix applies the HasSuffix predicate on the "salesperson_id" field.
func SalespersonIDHasSuffix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasSuffix(FieldSalespersonID, v))
}

// SalespersonIDIsNil applies the IsNil predicate on the "salesperson_id" field.
func SalespersonIDIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldSalespersonID))
}

// SalespersonIDNotNil applies the NotNil predicate on the "salesperson_id" field.
func SalespersonIDNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldSalespersonID))
}

// SalespersonIDEqualFold applies the EqualFold predicate on the "salesperson_id" field.
func SalespersonIDEqualFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEqualFold(FieldSalespersonID, v))
}

// SalespersonIDContainsFold applies the ContainsFold predicate on the "salesperson_id" field.
func SalespersonIDContainsFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContainsFold(FieldSalespersonID, v))
}

// DealNumberEQ applies the EQ predicate on the "deal_number" field.
func DealNumberEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldDealNumber, v))
}

// DealNumberNEQ applies the NEQ predicate on the "deal_number" field.
func DealNumberNEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldDealNumber, v))
}

// DealNumberIn applies the In predicate on the "deal_number" field.
func DealNumberIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldDealNumber, vs...))
}

// DealNumberNotIn applies the NotIn predicate on the "deal_number" field.
func DealNumberNotIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldDealNumber, vs...))
}

// DealNumberGT applies the GT predicate on the "deal_number" field.
func DealNumberGT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldDealNumber, v))
}

// DealNumberGTE applies the GTE predicate on the "deal_number" field.
func DealNumberGTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldDealNumber, v))
}

// DealNumberLT applies the LT predicate on the "deal_number" field.
func DealNumberLT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldDealNumber, v))
}

// DealNumberLTE applies the LTE predicate on the "deal_number" field.
func DealNumberLTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldDealNumber, v))
}

// DealNumberContains applies the Contains predicate on the "deal_number" field.
func DealNumberContains(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContains(FieldDealNumber, v))
}

// DealNumberHasPrefix applies the HasPrefix predicate on the "deal_number" field.
func DealNumberHasPrefix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasPrefix(FieldDealNumber, v))
}

// DealNumberHasSuffix applies the HasSuffix predicate on the "deal_number" field.
func DealNumberHasSuffix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasSuffix(FieldDealNumber, v))
}

// DealNumberEqualFold applies the EqualFold predicate on the "deal_number" field.
func DealNumberEqualFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEqualFold(FieldDealNumber, v))
}

// DealNumberContainsFold applies the ContainsFold predicate on the "deal_number" field.
func DealNumberContainsFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContainsFold(FieldDealNumber, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContainsFold(FieldStatus, v))
}

// StageEQ applies the EQ predicate on the "stage" field.
func StageEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldStage, v))
}

// StageNEQ applies the NEQ predicate on the "stage" field.
func StageNEQ(v string) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldStage, v))
}

// StageIn applies the In predicate on the "stage" field.
func StageIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldStage, vs...))
}

// StageNotIn applies the NotIn predicate on the "stage" field.
func StageNotIn(vs ...string) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldStage, vs...))
}

// StageGT applies the GT predicate on the "stage" field.
func StageGT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldStage, v))
}

// StageGTE applies the GTE predicate on the "stage" field.
func StageGTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldStage, v))
}

// StageLT applies the LT predicate on the "stage" field.
func StageLT(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldStage, v))
}

// StageLTE applies the LTE predicate on the "stage" field.
func StageLTE(v string) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldStage, v))
}

// StageContains applies the Contains predicate on the "stage" field.
func StageContains(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContains(FieldStage, v))
}

// StageHasPrefix applies the HasPrefix predicate on the "stage" field.
func StageHasPrefix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasPrefix(FieldStage, v))
}

// StageHasSuffix applies the HasSuffix predicate on the "stage" field.
func StageHasSuffix(v string) predicate.Deal {
	return predicate.Deal(sql.FieldHasSuffix(FieldStage, v))
}

// StageEqualFold applies the EqualFold predicate on the "stage" field.
func StageEqualFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldEqualFold(FieldStage, v))
}

// StageContainsFold applies the ContainsFold predicate on the "stage" field.
func StageContainsFold(v string) predicate.Deal {
	return predicate.Deal(sql.FieldContainsFold(FieldStage, v))
}

// SalePriceEQ applies the EQ predicate on the "sale_price" field.
func SalePriceEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldSalePrice, v))
}

// SalePriceNEQ applies the NEQ predicate on the "sale_price" field.
func SalePriceNEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldSalePrice, v))
}

// SalePriceIn applies the In predicate on the "sale_price" field.
func SalePriceIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldSalePrice, vs...))
}

// SalePriceNotIn applies the NotIn predicate on the "sale_price" field.
func SalePriceNotIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldSalePrice, vs...))
}

// SalePriceGT applies the GT predicate on the "sale_price" field.
func SalePriceGT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldSalePrice, v))
}

// SalePriceGTE applies the GTE predicate on the "sale_price" field.
func SalePriceGTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldSalePrice, v))
}

// SalePriceLT applies the LT predicate on the "sale_price" field.
func SalePriceLT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldSalePrice, v))
}

// SalePriceLTE applies the LTE predicate on the "sale_price" field.
func SalePriceLTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldSalePrice, v))
}

// SalePriceIsNil applies the IsNil predicate on the "sale_price" field.
func SalePriceIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldSalePrice))
}

// SalePriceNotNil applies the NotNil predicate on the "sale_price" field.
func SalePriceNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldSalePrice))
}

// DownPaymentEQ applies the EQ predicate on the "down_payment" field.
func DownPaymentEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldDownPayment, v))
}

// DownPaymentNEQ applies the NEQ predicate on the "down_payment" field.
func DownPaymentNEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldDownPayment, v))
}

// DownPaymentIn applies the In predicate on the "down_payment" field.
func DownPaymentIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldDownPayment, vs...))
}

// DownPaymentNotIn applies the NotIn predicate on the "down_payment" field.
func DownPaymentNotIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldDownPayment, vs...))
}

// DownPaymentGT applies the GT predicate on the "down_payment" field.
func DownPaymentGT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldDownPayment, v))
}

// DownPaymentGTE applies the GTE predicate on the "down_payment" field.
func DownPaymentGTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldDownPayment, v))
}

// DownPaymentLT applies the LT predicate on the "down_payment" field.
func DownPaymentLT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldDownPayment, v))
}

// DownPaymentLTE applies the LTE predicate on the "down_payment" field.
func DownPaymentLTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldDownPayment, v))
}

// DownPaymentIsNil applies the IsNil predicate on the "down_payment" field.
func DownPaymentIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldDownPayment))
}

// DownPaymentNotNil applies the NotNil predicate on the "down_payment" field.
func DownPaymentNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldDownPayment))
}

// AmountFinancedEQ applies the EQ predicate on the "amount_financed" field.
func AmountFinancedEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldAmountFinanced, v))
}

// AmountFinancedNEQ applies the NEQ predicate on the "amount_financed" field.
func AmountFinancedNEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldAmountFinanced, v))
}

// AmountFinancedIn applies the In predicate on the "amount_financed" field.
func AmountFinancedIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldAmountFinanced, vs...))
}

// AmountFinancedNotIn applies the NotIn predicate on the "amount_financed" field.
func AmountFinancedNotIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldAmountFinanced, vs...))
}

// AmountFinancedGT applies the GT predicate on the "amount_financed" field.
func AmountFinancedGT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldAmountFinanced, v))
}

// AmountFinancedGTE applies the GTE predicate on the "amount_financed" field.
func AmountFinancedGTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldAmountFinanced, v))
}

// AmountFinancedLT applies the LT predicate on the "amount_financed" field.
func AmountFinancedLT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldAmountFinanced, v))
}

// AmountFinancedLTE applies the LTE predicate on the "amount_financed" field.
func AmountFinancedLTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldAmountFinanced, v))
}

// AmountFinancedIsNil applies the IsNil predicate on the "amount_financed" field.
func AmountFinancedIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldAmountFinanced))
}

// AmountFinancedNotNil applies the NotNil predicate on the "amount_financed" field.
func AmountFinancedNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldAmountFinanced))
}

// MonthlyPaymentEQ applies the EQ predicate on the "monthly_payment" field.
func MonthlyPaymentEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldMonthlyPayment, v))
}

// MonthlyPaymentNEQ applies the NEQ predicate on the "monthly_payment" field.
func MonthlyPaymentNEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldMonthlyPayment, v))
}

// MonthlyPaymentIn applies the In predicate on the "monthly_payment" field.
func MonthlyPaymentIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldMonthlyPayment, vs...))
}

// MonthlyPaymentNotIn applies the NotIn predicate on the "monthly_payment" field.
func MonthlyPaymentNotIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldMonthlyPayment, vs...))
}

// MonthlyPaymentGT applies the GT predicate on the "monthly_payment" field.
func MonthlyPaymentGT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldMonthlyPayment, v))
}

// MonthlyPaymentGTE applies the GTE predicate on the "monthly_payment" field.
func MonthlyPaymentGTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldMonthlyPayment, v))
}

// MonthlyPaymentLT applies the LT predicate on the "monthly_payment" field.
func MonthlyPaymentLT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldMonthlyPayment, v))
}

// MonthlyPaymentLTE applies the LTE predicate on the "monthly_payment" field.
func MonthlyPaymentLTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldMonthlyPayment, v))
}

// MonthlyPaymentIsNil applies the IsNil predicate on the "monthly_payment" field.
func MonthlyPaymentIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldMonthlyPayment))
}

// MonthlyPaymentNotNil applies the NotNil predicate on the "monthly_payment" field.
func MonthlyPaymentNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldMonthlyPayment))
}

// TermMonthsEQ applies the EQ predicate on the "term_months" field.
func TermMonthsEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldTermMonths, v))
}

// TermMonthsNEQ applies the NEQ predicate on the "term_months" field.
func TermMonthsNEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldTermMonths, v))
}

// TermMonthsIn applies the In predicate on the "term_months" field.
func TermMonthsIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldTermMonths, vs...))
}

// TermMonthsNotIn applies the NotIn predicate on the "term_months" field.
func TermMonthsNotIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldTermMonths, vs...))
}

// TermMonthsGT applies the GT predicate on the "term_months" field.
func TermMonthsGT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldTermMonths, v))
}

// TermMonthsGTE applies the GTE predicate on the "term_months" field.
func TermMonthsGTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldTermMonths, v))
}

// TermMonthsLT applies the LT predicate on the "term_months" field.
func TermMonthsLT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldTermMonths, v))
}

// TermMonthsLTE applies the LTE predicate on the "term_months" field.
func TermMonthsLTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldTermMonths, v))
}

// TermMonthsIsNil applies the IsNil predicate on the "term_months" field.
func TermMonthsIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldTermMonths))
}

// TermMonthsNotNil applies the NotNil predicate on the "term_months" field.
func TermMonthsNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldTermMonths))
}

// InterestRateEQ applies the EQ predicate on the "interest_rate" field.
func InterestRateEQ(v float64) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldInterestRate, v))
}

// InterestRateNEQ applies the NEQ predicate on the "interest_rate" field.
func InterestRateNEQ(v float64) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldInterestRate, v))
}

// InterestRateIn applies the In predicate on the "interest_rate" field.
func InterestRateIn(vs ...float64) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldInterestRate, vs...))
}

// InterestRateNotIn applies the NotIn predicate on the "interest_rate" field.
func InterestRateNotIn(vs ...float64) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldInterestRate, vs...))
}

// InterestRateGT applies the GT predicate on the "interest_rate" field.
func InterestRateGT(v float64) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldInterestRate, v))
}

// InterestRateGTE applies the GTE predicate on the "interest_rate" field.
func InterestRateGTE(v float64) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldInterestRate, v))
}

// InterestRateLT applies the LT predicate on the "interest_rate" field.
func InterestRateLT(v float64) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldInterestRate, v))
}

// InterestRateLTE applies the LTE predicate on the "interest_rate" field.
func InterestRateLTE(v float64) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldInterestRate, v))
}

// InterestRateIsNil applies the IsNil predicate on the "interest_rate" field.
func InterestRateIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldInterestRate))
}

// InterestRateNotNil applies the NotNil predicate on the "interest_rate" field.
func InterestRateNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldInterestRate))
}

// GrossProfitEQ applies the EQ predicate on the "gross_profit" field.
func GrossProfitEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldGrossProfit, v))
}

// GrossProfitNEQ applies the NEQ predicate on the "gross_profit" field.
func GrossProfitNEQ(v int) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldGrossProfit, v))
}

// GrossProfitIn applies the In predicate on the "gross_profit" field.
func GrossProfitIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldGrossProfit, vs...))
}

// GrossProfitNotIn applies the NotIn predicate on the "gross_profit" field.
func GrossProfitNotIn(vs ...int) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldGrossProfit, vs...))
}

// GrossProfitGT applies the GT predicate on the "gross_profit" field.
func GrossProfitGT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldGrossProfit, v))
}

// GrossProfitGTE applies the GTE predicate on the "gross_profit" field.
func GrossProfitGTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldGrossProfit, v))
}

// GrossProfitLT applies the LT predicate on the "gross_profit" field.
func GrossProfitLT(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldGrossProfit, v))
}

// GrossProfitLTE applies the LTE predicate on the "gross_profit" field.
func GrossProfitLTE(v int) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldGrossProfit, v))
}

// GrossProfitIsNil applies the IsNil predicate on the "gross_profit" field.
func GrossProfitIsNil() predicate.Deal {
	return predicate.Deal(sql.FieldIsNull(FieldGrossProfit))
}

// GrossProfitNotNil applies the NotNil predicate on the "gross_profit" field.
func GrossProfitNotNil() predicate.Deal {
	return predicate.Deal(sql.FieldNotNull(FieldGrossProfit))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Deal {
	return predicate.Deal(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := newCustomerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVehicle applies the HasEdge predicate on the "vehicle" edge.
func HasVehicle() predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VehicleTable, VehicleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVehicleWith applies the HasEdge predicate on the "vehicle" edge with a given conditions (other predicates).
func HasVehicleWith(preds ...predicate.Vehicle) predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := newVehicleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSalesperson applies the HasEdge predicate on the "salesperson" edge.
func HasSalesperson() predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SalespersonTable, SalespersonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSalespersonWith applies the HasEdge predicate on the "salesperson" edge with a given conditions (other predicates).
func HasSalespersonWith(preds ...predicate.User) predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := newSalespersonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTradeIns applies the HasEdge predicate on the "trade_ins" edge.
func HasTradeIns() predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TradeInsTable, TradeInsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTradeInsWith applies the HasEdge predicate on the "trade_ins" edge with a given conditions (other predicates).
func HasTradeInsWith(preds ...predicate.TradeIn) predicate.Deal {
	return predicate.Deal(func(s *sql.Selector) {
		step := newTradeInsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Deal) predicate.Deal {
	return predicate.Deal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Deal) predicate.Deal {
	return predicate.Deal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Deal) predicate.Deal {
	return predicate.Deal(sql.NotPredicates(p))
}
